### ISSUE TITLE
k-odyssey.com

### ISSUE THREAD

**Issue by JustLurkingHere** [qsniyg/maxurl#1096]
From site https://k-odyssey.com/

URL is https://k-odyssey.com/news/data/20221127/p1065571988697032_786_thum.jpg 

It must be https://k-odyssey.com/news/data/20221127/p1065571988697032_786.jpg to get the original resolution.

Thank you so much

**Comment by qsniyg** [comment]
Sorry for the late reply. For some reason the example URL you linked returns 404 for me (maybe it expired?).

The userscript should support k-odyssey.com (I just tried with a few other URLs on the website). It does also try to redirect the `_thum` link you sent to the full link, but fails due to the 404 error.

I'll close the issue as I believe it should be supported, but if it isn't please let me know and I'll reopen :)
