### ISSUE TITLE
Png cover on bandcamp

### ISSUE THREAD

**Issue by bebound** [qsniyg/maxurl#116]
Currently, we're using jpg, but png cover is also available on bandcamp.
Usually, png has better quality.
ex:
https://f4.bcbits.com/img/a2548555749_1.png
https://f4.bcbits.com/img/a2548555749_0.jpg

**Comment by qsniyg** [comment]
Interesting, I have no issue adding it, but both images you posted (assuming _1.png is replaced to _0.png) are identical in quality (if you open both in an image editor, set the layer mode of one to subtract, and turn the contrast up very high, in this case it still remains completely black).

I also tried this with two other sets of images: https://f4.bcbits.com/img/0012903078_0.jpg and https://f4.bcbits.com/img/a0452005993_0.jpg, and was unable to find any difference with them either.

If you find an image where the quality is affected, please let me know and I'll update the rule :)

**Comment by bebound** [comment]
I guess you downloaded the wrong file. The jpg file we're using is 1.5M, and the png file is 2.7M.

I also can't identify the difference between these two pictures by eyes, but the diff tools shows they're not the same.
<img width="764" alt="Screen Shot 2019-09-03 at 23 36 23" src="https://user-images.githubusercontent.com/2227874/64187709-ae410a80-cea3-11e9-8fb6-b2705e2732f0.png">

**Comment by qsniyg** [comment]
So it turns out the extension doesn't matter (even `.asdf` will work), what matters is `_1` and `_0` (that was my fault, sorry!). In the image you linked, `_1` is a PNG, and `_0` is a JPG, but for another image (https://f4.bcbits.com/img/0012903078_0.jpg), both are PNGs, but `_1` is the smaller one (both have identical pixels however).

However, I still don't see the difference you're seeing with the image you sent. I downloaded both using wget (and also the browser, to see if that had any difference), and after turning the contrast up to 255 (the largest value), all I got was a random array of pixels:

![bandcamp_randompixels](https://user-images.githubusercontent.com/20496822/64198913-0cd39d80-ce3e-11e9-89b3-188042648412.png)

Would you mind attaching both files to Github (or some other online file storage service) instead? I really don't understand what's going on and why I can't replicate the result you're seeing, sorry.

It could be that `_0` is the original file, and `_1` is the file automatically converted to PNG by Bandcamp's servers. However, that would not necessarily explain the result you got in that picture (although it could also be that it internally converts it to JPG, then for some reason finally into PNG -- I am not by any means an expert on image formats however, so I could be entirely wrong here).

**Comment by bebound** [comment]
https://f4.bcbits.com/img/0012903078_0.jpg
In this image, the diff tool show the only difference is their brightness.
<img width="377" alt="Screen Shot 2019-09-04 at 11 54 59 AM" src="https://user-images.githubusercontent.com/2227874/64224788-648c0a80-cf0b-11e9-8918-48bb0546aa0b.png">

Here are the 2548555749 covers I get, https://www.dropbox.com/s/c22r4y9pfid0x9i/bandcamp.zip?dl=0

I also suspect that 1.png was converted from 0.jpg. As if convert jpg to png, these two png are quiet similar, that's abnormal. Why did bandcamp do this...

a2548555749_1.png vs jpg->png
<img width="513" alt="Screen Shot 2019-09-04 at 12 08 07 PM" src="https://user-images.githubusercontent.com/2227874/64225149-bda86e00-cf0c-11e9-92cf-359ee28e56fd.png">

**Comment by qsniyg** [comment]
So I downloaded the files you shared, but the result is the same as before. What diff tool are you using to do this? I'm using GIMP.

I decided to try converting both to PNMs (uncompressed raw images), and the files are identical (`diff *.pnm` returns nothing).

My guess is that this means the images are indeed identical, and the brightness differences we're seeing is some kind of issue in color space. You can see this in your browser if you check https://f4.bcbits.com/img/a0452005993_10.jpg and https://f4.bcbits.com/img/a0452005993_0.jpg, the second will look more saturated than the first, even though the image itself not (it's an issue with the browser's interpretation of the color space). This doesn't explain the random noise however, but this might just be an issue with one of the tool's interpretation of the JPG file or something? Again, I'm not an expert on image formats, but seeing as how in order to see the noise, you have to turn the contrast up extremely high, I'm pretty sure this isn't quality, but rather some kind of error.

Also maybe interesting to note, I converted the images using graphicsmagick (imagemagick fork), the same engine that Imgur and many other websites use. Using the images graphicsmagick converted, the images were entirely identical, meaning that it could be that graphicsmagick interprets JPGs in a different way than GIMP does, and assuming Bandcamp uses graphicsmagick to convert the images automatically, this may explain the random noise we're seeing.

**Comment by bebound** [comment]
I'm using [kaleidoscope](https://www.kaleidoscopeapp.com/). I just realized that the _brightness difference_ in kaleidoscope means identical.

You're correct, bandcamp uses graphicsmagick to convert `0.jpg`/`0.png` to `1.png`. 

Thank you so much.
