### ISSUE TITLE
Support host.church (formerly jpg.church)

### ISSUE THREAD

**Issue by beeznutsonly** [qsniyg/maxurl#1274]
NB: Host migrated from previously supported (#1161) `jpg.church` to new `host.church`.

---

## Example 1

Thumbnail size: `https://simp4.host.church/5de4afeeda99c.th.jpg`
Medium size: `https://simp4.host.church/5de4afeeda99c.md.jpg`
Full size: `https://simp4.host.church/5de4afeeda99c.jpg`

## Example 2

Thumbnail size: `https://simp6.host.church/images/36d8a45cf8a6079b35691bb6dcf50d08.jpeg1000w_0e_2776820.th.jpg`
Medium size: `https://simp6.host.church/images/36d8a45cf8a6079b35691bb6dcf50d08.jpeg1000w_0e_2776820.md.jpg`
Full size: `https://simp6.host.church/images/36d8a45cf8a6079b35691bb6dcf50d08.jpeg1000w_0e_2776820.jpg`

**Comment by qsniyg** [comment]
@SakalliTavernaci Do you mean redirecting `jpg.church` URLs to `host.church` URLs?

**Comment by qsniyg** [comment]
Should be fixed with: https://github.com/qsniyg/maxurl/commit/fe80c24232c8806b77281601df8d5797a2aa5dcf

**Comment by qsniyg** [comment]
@SakalliTavernaci Do you have the latest git version installed?

It won't redirect an HTML page unless `Redirect for HTML pages too` is enabled (I wouldn't recommend enabling the option though, otherwise sites like Imgur and YouTube will also start redirecting to their main images/videos). However, if it's linked somewhere, the popup should work fine. You can also enable `Popup page URL` and use the popup on the HTML page, and it should return the `host.church` URL.
