### ISSUE TITLE
iTunes image quality option 

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#164]
iTunes images such as
```
https://is5-ssl.mzstatic.com/image/thumb/Music123/v4/77/50/9d/77509d7c-812f-3c35-69f4-cf6176b0eaaa/COZX-1593.jpg/999999999x0w.jpg
```
can have an optional quality parameter (`-{q}`) at the end. the default (no parameter) is 80.

```
https://is5-ssl.mzstatic.com/image/thumb/Music123/v4/77/50/9d/77509d7c-812f-3c35-69f4-cf6176b0eaaa/COZX-1593.jpg/999999999x0w-100.jpg
```

This will return best quality jpeg (100). Any number beyond 100 will return the same highest one.

Currently, `999999999x0w-100.jpg` will redirect back to `999999999x0w.jpg` which gives worse quality (because default is 80).

I think we can either always jump to -100 or simply don't touch that parameter, so users can keep whatever quality they want.

**Comment by fireattack** [comment]
Side note: this parameter makes no difference for .png file, obviously.

**Comment by qsniyg** [comment]
Thanks! I've added it in :) Turns out one of the test images (http://is5.mzstatic.com/image/thumb/Music62/v4/0b/1f/36/0b1f364c-cc8f-1c8c-74a4-70cfb01d8ef4/source/100000x100000-999.jpg) had -999 as the quality option, so I'll leave it there, in the off chance that it actually is better than -100 (doubt it, but as you said, it doesn't hurt either)
