### ISSUE TITLE
[Twitter] some :orig sized images are missing

### ISSUE THREAD

**Issue by MeatyChunks** [qsniyg/maxurl#167]
A lot of Twitter images aren't showing for the past few days, Firefox says they contain errors. Of the quick scan I did I could only find this one that actually shows:
https://pbs.twimg.com/media/EK2NmQmX0AAOFRP.png

Some errored examples:
https://pbs.twimg.com/media/EK2J_glWkAAlVUX.png?name=orig
https://pbs.twimg.com/media/EK2OTJ3WoAABdYR.png?name=orig

Using Firefox Nightly 2019-12-02 and version 0.11.14 of the addon. Thanks!

**Comment by qsniyg** [comment]
Sorry, I don't quite understand what's going on...

Although I haven't tested with the nightly yet (I will soon), trying:

https://pbs.twimg.com/media/EK2J_glWkAAlVUX.png

Redirects to

https://pbs.twimg.com/media/EK2J_glWkAAlVUX.jpg?name=orig

Which works fine on my end (although `.png?name=orig` doesn't, as you mentioned).

To try to understand the problem, if you go to the first link (`.png` without `?name=orig`), does it redirect properly? How did you end up with the last two URLs?

To clarify a little, the reason I'm confused is not because it shouldn't output the two URLs - they are the first ones IMU tries (which changed in 0.11.14). The issue is that IMU shouldn't redirect (or use) those URLs if they are broken (which it checks through HEAD requests), and should instead try the .jpg equivalents.

Are you using any special tracking protection configuration as well, or just the standard?

**Comment by MeatyChunks** [comment]
Hi, thanks for the quick response! I made sure it wasn't some other addon interfering at least by using safe mode, and my tracking is set to high. I think you're on to something with how I access the image though, I was using right click -> view image which spits out a URL with a format parameter which it seems to ignore. The tweet I used is https://twitter.com/ispreview/status/1201768401376546816 and you can see it gives me "https://pbs.twimg.com/media/EK2J_glWkAAlVUX?format=jpg&name=small" but redirects to a png version still which causes the error.

**Comment by qsniyg** [comment]
@MeatyChunks Thank you! Yep, it was high tracking protection that caused the issue. Will try to see if I can fix it on my end :)

**Comment by MeatyChunks** [comment]
Ah, thank you. That's a shame, seems like I can't just untick it for twimg and twitter either? Setting it to custom and disabling tracking content did make it work though, you're right.

**Comment by qsniyg** [comment]
I'm not quite sure, it doesn't seem to be possible. Disabling tracking protection for twimg doesn't seem to do anything either (although I believe that's because the requests are made from the extension's context, not from the twimg context).

As I don't think there's anything I can do on my end about it, I've disabled redirecting if it appears to be blocked. This being said, you can still use the popup if you disable "Wait until image is fully loaded" (this will force the request to be done through the browser's context instead, which works at least on my end).

**Comment by qsniyg** [comment]
The issue is fixed in 0.11.15

Everything should work properly now, at least for Twitter (without needing to enable the "Wait until image is fully loaded" option either). If it can't load the image through the extension, it will try to load it through the browser instead.
