### ISSUE TITLE
Add support for oclc.org and wsimg.com

### ISSUE THREAD

**Issue by rahidz** [qsniyg/maxurl#21]
Examples:

http://cdm16622.contentdm.oclc.org/utils/ajaxhelper/?CISOROOT=gokfa&CISOPTR=973&action=2&DMSCALE=20&DMWIDTH=213&DMHEIGHT=400&DMX=0&DMY=0&DMTEXT=&DMROTATE=0

to

http://cdm16622.contentdm.oclc.org/utils/ajaxhelper/?CISOROOT=gokfa&CISOPTR=973&action=2&DMSCALE=200&DMWIDTH=9999&DMHEIGHT=9999&DMX=0&DMY=0&DMTEXT=&DMROTATE=0

DMSCALE goes up (not sure if it's always 200), DMWIDTH and DMHEIGHT can be maximized, DMX and DMY should always start at 0.

and

https://img1.wsimg.com/isteam/ip/84d1b722-4195-4c8a-993f-be0ddc84a927/4b9436b1-b3d3-4e13-9fba-533e632780d2.jpg/:/rs=w:400,h:500,cg:true,m/cr=w:800,h:500,a:cc

to

https://img1.wsimg.com/isteam/ip/84d1b722-4195-4c8a-993f-be0ddc84a927/4b9436b1-b3d3-4e13-9fba-533e632780d2.jpg/:/rs=w:9999,h:9999,cg:true,m/cr=w:9999,h:9999,a:cc

where w and h values in both cases are changed to 9999 or another high number.

**Comment by qsniyg** [comment]
Thank you very much for sharing these!

After doing a bit more research, I modified the rules slightly from what you suggested. The first one is one of many different URLs supported from OCLC that also uses IIIF, a really neat API that allows you to get the original image, so I redirected it to that one instead.

For the second, after looking at another, smaller image, it turns out that using `rs=w:9999` stretches it, so I removed the entire `/:/rs=...` query, and it seems to work. However, it doesn't seem to be the original version, as there are other patterns that support larger images (although I wasn't able to find a way to get it to work with the `isteam` images unfortunately), and the images with this one seem to be cut off at a maximum of 2560 on either side.

**Comment by qsniyg** [comment]
Interestingly enough, http://digital.denverlibrary.org/digital/iiif/p16079coll39/936/full/full/0/default.jpg rescales it to a width of 9000 (the original width being 12085)

The original file (http://worldcat.org/digitalarchive/viewmaster/server16079.contentdm.oclc.org/DPL/p16079coll39/CDI/1493140873122/map_2017_124.tif) cannot be found via URL hacks (I believe), but it can be found through the original page (http://digital.denverlibrary.org/cdm/ref/collection/p16079coll39/id/936), which itself can be found through URL hacks (although only for the Denver Library in this case).

Using /api/singleitem/image, as was used in the old rule, results in: http://digital.denverlibrary.org/digital/api/singleitem/image/p16079coll39/936/default.jpg (730x503).

I'll have to find some kind of better solution.
