### ISSUE TITLE
Download behavior not as expected in Firefox

### ISSUE THREAD

**Issue by elihorn** [qsniyg/maxurl#215]
Download (via link or shortcut key) opens the image in the browser rather than forcing a download. Perhaps this is a matter of preference but a direct download very convenient for quickly grabbing many images. For reference, both Imagus and HoverZoom+ behave this way.

**Comment by qsniyg** [comment]
@elihorn Which website do you encounter this on? I know some websites have this issue due to (I believe) CSP-related issues, but I haven't yet tracked down the cause. Also, are you using the extension or the userscript?

I believe a proper solution would be to force override the content-disposition header for the extension, although obviously that wouldn't work for the userscript. Problem is though, for the userscript, GM_download (the function that would _seem_ to do what is wanted) is usually just implemented using the `<a>` tag trick (e.g. that's how Violentmonkey does it), so for those specific websites where it doesn't work, GM_download probably won't work either unfortunately. I guess it's up to them to fix it though, and I should just use GM_download anyways haha.

**Comment by elihorn** [comment]
Thanks for the quick response! I was using the addon but I just tried the userscript to see if there was a difference. It seem like images download automatically with the userscript, it's only with the addon that they open in the browser window.

So far I've tried Google Images, DuckDuckGo Images, Wikipedia, Instagram, Flickr, all with the same behavior.

**Comment by qsniyg** [comment]
Good to know! I'm able to replicate the issue on my end. I'm not quite sure what is causing it, but I'll be able to implement a proper fix for the extension, hopefully tomorrow :)

**Comment by qsniyg** [comment]
Fixed! It should always work for the extension now, regardless of the page's CSP :)
