### ISSUE TITLE
newTumbl.com rule upgrades wrongly to .mp4 urls

### ISSUE THREAD

**Issue by LeGiTiM** [qsniyg/maxurl#220]
Hi there!
First of all, thanks for the very active development and dedication, your work is very appreciated!

This report is about a rule applying to newtumbl.com (much better alternative to tumblr, features-wise, btw):
all media extensions (for images, gifs & videos) when opening in a new tab are changed to .mp4, which breaks gifs, and also saves wrongly .mp4 files (when it should be .jpg or .gif, etc) if we choose to download them locally on the computer.

The bug occurs on Firefox (extension) & Brave (script) for me (on Windows). Not tested in other browsers.

For users encountering the same bug, you can use this entry in your blacklist to ignore newtumbl pictures while we wait for a fix:
`dn*.newtumbl.com`

Thanks in advance to the dev!

**Comment by qsniyg** [comment]
Thank you very much for reporting!

I had changed it to always redirect to mp4 because some jpg's were actually just used as screenshots for mp4's. However, I hadn't thought of the filename issue you mentioned, or tested it with gifs.

Unfortunately newtumbl's images don't fail if you use the wrong extension, which means that any extension you throw at it will "work" (an image will be loaded), but for mp4 and gif files, only loading the .mp4 or .gif extension will return the proper image.

The way it works now is that it will test both the mp4 and the gif URL to see what `content-type` is returned. If the mp4 returns a video, then the link must be a video, but if it returns an image, then it tries the gif extension instead, which will either return `image/gif` or `image/jpg`.

If you encounter any other issues, please let me know! I've tested with a jpg, an mp4, and a gif, but there might be some edge-case I haven't yet found :)
