### ISSUE TITLE
Keybindings on the numeric keypad are messed up

### ISSUE THREAD

**Issue by LeGiTiM** [qsniyg/maxurl#234]
Hi there!

Category of the bug: not critical, neither very hindering, just weird.

Description of the bug: when attempting to set a customized keybind for any action with the numeric keypad, the numbers appearing on the options are not the same as what was typed. It's as if the numpad was shifted of 1 row (the row of 7,8,9 is not supported by the option page [can't bind these keys], and 4,5,6 are misinterpreted as 7,8,9. 0 is considered as a 3, as a consequence, for example).

This bug occurs within the extension and the script.

**Comment by qsniyg** [comment]
Thank you very much for reporting! For whatever reason, I hadn't actually tested the numpad numbers, turns out they have a different keycode associated.

The shifting by a row is quite an interesting bug, it's caused by me stupidly assuming javascript would return uppercase keys when shift was pressed, so if it was within a sort of uppercase range, it would try to "convert it to lowercase". However, where the lowercase ASCII codes are happens to be where the numpad keys are in javascript's event mapping.
