### ISSUE TITLE
Change the location of the popup UI

### ISSUE THREAD

**Issue by A-Sparowe** [qsniyg/maxurl#247]
Is it possible to change the default location of the popup ui buttons? like from top to left or right side?

**Comment by qsniyg** [comment]
Not yet, but that's a good idea! I probably won't be able to add the feature right yet, as it would require a bit of refactoring, but it'll likely be implemented alongside fixing #218 

Thanks for the suggestion!

**Comment by xXReDxSparoweXx** [comment]
Nice!

**Comment by qsniyg** [comment]
Sorry for getting back so late! It's finally implemented now :) https://github.com/qsniyg/maxurl/commit/e22ec12fda40af9b1380ca49dd7b188237c74537

Basically, in the Button CSS style, you add (for example):

```
#closebtn {
  -imu-pos: bottom-middle
}
```

Possible values are:

 * `top-left`, `top-middle`, `top-right`
 * `left`, `middle`, `right`
 * `bottom-left`, `bottom-middle`, `bottom-right`

It's still a little rough around the edges for the moment:

 * Adding multiple items to the vertical middle (`left`, `middle`, `right`) will result in them being added horizontally rather than vertically, which is likely not wanted
 * Vertical/horizontal middle is incorrect before it's zoomed
 * The caption element automatically updates its "short" text based on the length of the top-left container, so it might be incorrect if it's moved somewhere else

However, these should hopefully be fixed soon :)

There are also a few missing features I plan to address soon:

 * Setting the origin for the button (whether the middle of the button should be the middle of the container, or top-left/bottom-right etc.)
 * Reordering the buttons (they're currently added in a fixed order, e.g. close will always be the first button of any container it's added to)
 * Anything else?
