### ISSUE TITLE
The blacklist and websites

### ISSUE THREAD

**Issue by liraqb** [qsniyg/maxurl#273]
1. Blacklist is invalid.
1. Pornhub: The cover will not pop up, the video is popped up with no picture and only sound. If you use the "New tap" method, the preview or video will be opened.
1. FC2動画アダルト: The cover will not pop up, the preview or video is popped up.

**Comment by qsniyg** [comment]
1. Try enabling "Don't popup blacklisted images". I should probably make that the default, as I agree, it's confusing otherwise. If it still doesn't work, could you send me your blacklist and which page it doesn't work for?
2. Yeah, that's because of adblockers... I don't know if it's possible to fix this. Maybe they could add a rule to exclude this userscript's popup element, but then again, pornhub might exploit that by making something look like this userscript's popup element...
3. Could you send me a link to a page that doesn't work? The few pages I tried it on worked fine for me, but I know that each page can be quite different from each other.

Thanks for reporting these issues! :)

**Comment by qsniyg** [comment]
The second issue (the video being hidden) should now be fixed :) https://github.com/qsniyg/maxurl/commit/e66dfa44bb232862d1ce24e48a4feb44e16173d7
