### ISSUE TITLE
recochoku.jp

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#276]
Example link: https://recochoku.jp/song/S1008963961/

Image resources such as 
`https://img.lap.recochoku.jp/p1/imgkp?p=%2F12%2F9512%2F157791228.jpg&f=736E79&FFh=300&FFw=300&h=258B7&option=FFenl%3Don`

To 

`https://img.lap.recochoku.jp/p1/imgkp?p=%2F12%2F9512%2F157791228.jpg&f=736E79&FFh=9999&FFw=9999`

(`h` and `option` don't seem to matter, but `f`, `FFh` and `FFw` must be kept.)

**Comment by qsniyg** [comment]
Thank you very much as usual! :)

Unfortunately I couldn't find anywhere where the paths lead to, was hoping it'd be possible to just redirect to the original path, but no such luck so far.

Since it seems like they've written their own system (`recochoku.fpgapp.user.servlet.FPGImageKpBinaryServlet.doGet(FPGImageKpBinaryServlet.java:111)`), I don't think it'll be possible to get any hints from anywhere else unfortunately.

In any case, the rule will remove everything other than `p`, `f`, `FFh`, and `FFw`, and replace the last two with `999999999`, which appears to be among the largest numbers it supports (I guess something like INT_MAX might be supported as well from the error message, but I think 999999999 should suffice haha)
