### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by Nogooduser** [qsniyg/maxurl#28]
I've always loved using the max image url extension on Firefox since it lets me quickly open the image in a new tab via shortcut, but recently I've had to move to Chrome due to some complications with Firefox and I realized just how much I miss this feature in particular and I have no way to get it back.

It doesn't seem like it is possible to open an image in a new tab via a short cut with the script alone (or at least I couldn't find it in the settings page) which means that when using Chrome (or any chromium browser) there's no way to set a shortcut to open an image in a new tab, meaning the pop up or the direct image redirect are the only methods available. 

The script is also somewhat slower than the extension.

So my question is are there any plans to create a Chrome extension that has the same set of features the Firefox one has?

**Comment by qsniyg** [comment]
I originally developed the extension under Chrome (although I haven't tested it recently under Chrome, it should still work), so it should work if you [sideload it](https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/). If you're unfamiliar, basically download the repository somehow, either through git or downloading+extracting the master zip, then enable developer mode, and select "Load unpacked extension", and navigate to the downloaded repository.

However, Google requires credit card information as well as a payment to upload to the Chrome web store, which, for various reasons, I'm uncomfortable with. So that's why it unfortunately has to be installed (and therefore updated) manually under Chrome.

**Comment by Nogooduser** [comment]
Seems to be working sideloaded, thanks! (though it did give me a small error related to geckoview, but after I cleared it it just worked as normal)
Though it's less convenient to have to update it manually I'm still glad I can use it in some form.

**Comment by qsniyg** [comment]
Due to #99 and Manifest v3, it's unfortunately relatively unlikely this will be published on the CWS at this point, even if it's possible to upload it.

I'm really disappointed in Google's decision here.

**Comment by liraqb** [comment]
The extension does not work on a Chromium kernel browser.

Browser: Cent Browser 4.1.7.182 (Chromium 78.0.3904.108)

The extension does not work, "Options" cannot be opened.

![](https://user-images.githubusercontent.com/62490653/77818554-52bfbe00-710e-11ea-8bee-e188e83d4e29.png)

The `chrome://extensions` page shows an error button. After clicking the error button, as shown below.

![](https://user-images.githubusercontent.com/62490653/77818560-5e12e980-710e-11ea-9dc5-569fd99700e2.png)

**Comment by qsniyg** [comment]
@liraqb Are you using the latest git version? In theory this issue should be fixed by https://github.com/qsniyg/maxurl/commit/942031c3689d14050b59490f0830064cfd712218 :)

If not, could you send me a screenshot of the error that's shown when clicking on the down arrow beside "extension_send_message is not a function"?

**Comment by liraqb** [comment]
It works now.

On Cent Browser 4.1.7.182 (Chromium 78.0.3904.108), there are only warning messages.

On Cent Browser 3.8.5.69 (Chromium 71.0.3578.98), there are warning messages and error messages.

It seems that the extension is running normally on both browsers.

Error messages changed. As shown below.

![Error messages](https://user-images.githubusercontent.com/62490653/77821058-0ed6b400-7122-11ea-804a-43944825c0e8.png)

**Comment by qsniyg** [comment]
@liraqb Interesting, I'm currently unable to test, but could you see if the latest commit fixes it?

**Comment by liraqb** [comment]
It's fixed.

**Comment by raisehero** [comment]
Hello, I'm suggesting to just release the extensions under this repository's release section.
Your situation is not unique, and many Chromium browser users (especially ungoogled-chromium users) do use https://github.com/NeverDecaf/chromium-web-store to update their extensions.
As I'm not familiar with extensions that updates via that extension updater, you probably need to consult that project.

**Comment by qsniyg** [comment]
@raisehero 

>I'm suggesting to just release the extensions under this repository's release section.

Though I'm doing git tags for releases, do you mean like proper github releases with `.crx` etc.? Good idea, I'll try to integrate that in the release workflow.

>As I'm not familiar with extensions that updates via that extension updater, you probably need to consult that project.

From a quick look, it appears to only work for addons that are using chrome web store... afaics it's impossible for an addon to automatically update itself, but what I've done for this one is to display (and optionally notify the user) available updates in the options tab. I could maybe add this as a badge to the extension too. Perhaps also link the .crx file instead of the repo for quicker updating?

**Comment by raisehero** [comment]
Yes, it does work for .crx. from GitHub releases. I used https://github.com/iamadamdev/bypass-paywalls-chrome and when Chromium Web Store updates the extention it will download from GitHub releases.

I'll open an issue to document how do one make their extension updatable with Chromium Web Store.

**Comment by raisehero** [comment]
@qsniyg https://github.com/NeverDecaf/chromium-web-store/commit/0464d762a6ee6073906e6550d975a12e0901502c

**Comment by qsniyg** [comment]
@raisehero Thank you! I'll try to implement this :)

**Comment by qsniyg** [comment]
~~Sorry for not getting back. I do plan on implementing this, I just have to get around to changing a few things and figuring out where to store things (as it'd be permanent). I've created a new issue for tracking this at #581~~ Implemented.

As for this issue, I'll close it as Google explicitly disallows extensions that enables downloading videos (section 4.4 of their webstore terms), and continues to often remove any extension that does so. So the chances of this getting added to the web store is pretty much zero at this point, unless they change their policies to be more permissive, which is... unlikely.

Just to be entirely clear: I have nothing against supporting chrome, and you can still sideload the extension. I'll work on the update thing so hopefully using the extension in a sideloaded form will be as easy as possible. It's just, afaik, impossible for the extension to be added to the web store, without rather seriously restricting its functionality, something which I'd rather not do.
