### ISSUE TITLE
Incorrect file name

### ISSUE THREAD

**Issue by liraqb** [qsniyg/maxurl#289]
I want to save the current pop-up picture directly instead of downloading it again from the link, so I use the "Save Image As..." and "Open Image in New Tab" to download, but the file name is incorrect.

**Comment by qsniyg** [comment]
Yeah, that's because it uses data URLs. As far as I know, there's unfortunately no way to fix this if data URLs are to be used, and save image as/open image in new tab is used (at least [not according to the spec](https://tools.ietf.org/html/rfc2397), and I couldn't find any resources online about it either), but it can be fixed in one of two ways:

 * You can use the download keys (S/Ctrl+S)/download button (if enabled in the UI section), or (as mentioned in your previous issue) the "Clicking link downloads" option, which will give the proper filename
 * Setting "Allow showing partially loaded" to "Media", which will load the image instead of the data URL. However, this will break a few images under the userscript version due to being unable to specify its headers (e.g. for websites that use anti-hotlink mechanisms).

**Comment by liraqb** [comment]
Thanks.
