### ISSUE TITLE
Video quality is not the highest

### ISSUE THREAD

**Issue by liraqb** [qsniyg/maxurl#290]
Video quality is not the highest on Youtube. It seems that the quality is selected according to the width of the largest cover.

**Comment by qsniyg** [comment]
Correct, this is related to #267 and #242. The second one is the main issue though, which also prevents it from supporting many sites, including Reddit's videos, Twitter videos (kind of), and possibly even FB videos (although it may still not be possible, even with that).

The reason is because Youtube only provides its higher resolutions through DASH videos, rather than a direct mp4 file.

The main issue I'm facing with supporting video streams is that downloading is significantly more complex, due to it needing to be done entirely in-browser (DASH/HLS streams are composed of usually thousands of individual parts, which all need to be assembled together), which would require a new UI for download, etc.

I guess I could just support them without supporting downloads for the time being, and add that feature later.

In any case, I'll see if I can implement it soon :)
