### ISSUE TITLE
Some old tumblr links not redirecting

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#3]
I don't know if this link has a raw version. But it's not at least redirecting to `1280`.

https://78.media.tumblr.com/tumblr_lyqq4hsfo01qdphnvo1_500.gif
https://78.media.tumblr.com/tumblr_mdsm9coSB41r06hrwo1_250.gif

**Comment by qsniyg** [comment]
Correct, the reason why is that there was a Tumblr GIF I found via the bot (before _raw was added) that didn't work with _1280, it would simply display a still image instead. Due to the suggestive nature of the image, I didn't add it to the script as a test case, but I since haven't been able to find another image that had the same problem, or, for that matter, that image again to test.

I believe it was one that could be redirected to a _raw (i.e. it had a path component between the domain and the filename, such as https://78.media.tumblr.com/3ebf4c3e175553194b3c9a0867a47719/tumblr_nugefiK7yj1u0c780o1_500.jpg), but I'm not sure if some GIFs might break like that other GIF if I add redirecting to 1280 for GIFs again, hence why I'm hesitating.

In the meantime, I'll see if I can find another GIF to replicate the problem.

**Comment by rEnr3n** [comment]
I found these animated gifs:
https://78.media.tumblr.com/b6a2ed8abae3e9f0a64ccc5bd14b5bbf/tumblr_n8w8k50vpR1r3kk98o1_250.gif
https://78.media.tumblr.com/a1dfad9537af0e38063ec186e2ff392e/tumblr_n87ft44o4Y1r3kk98o1_250.gif
https://68.media.tumblr.com/259f975e510edd376abce03f75087f21/tumblr_n6406ermsw1r3kk98o1_250.gif

Their 500 and 1280 versions are just still images. The script is currently redirecting them to raw which is animated.

It's a bit different for these ones:
https://78.media.tumblr.com/102fca5704db6aa1cc5e56ed7d9aa369/tumblr_n5ltfvGJC51r3kk98o1_250.gif
https://78.media.tumblr.com/257cce1bd6ec64e56b1c55129ddc547d/tumblr_n5lbkmnp5g1r3kk98o1_250.gif

The 250, 500, and 1280 versions are all still images. The script is redirecting them to raw which is the only animated one.

**Comment by qsniyg** [comment]
Thank you very much! After checking through a couple hundred images, I haven't yet found any case where redirecting to _1280 doesn't work for the other URLs (the ones that can't be redirected to _raw), and since the first photo I found was, I believe, not one of them either, I'll enable it for now. If you find any problems, let me know :)

**Comment by qsniyg** [comment]
Tumblr disabled the `_raw` endpoint last year, meaning this no longer works. The old issue where _1280 sometimes breaks a GIF is still present, so support for Tumblr GIFs must be manually enabled using the "Possibly broken images" option under the "Rules" category
