### ISSUE TITLE
Support Cloudimage 

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [qsniyg/maxurl#312]
`//token.cloudimg.io/v7/original_image_url?`
[source:](https://docs.cloudimage.io/go/cloudimage-documentation-v7/en/introduction)

**Comment by qsniyg** [comment]
Thank you!! Turns out I already had a cloudimage rule, but it didn't support the image resizing feature (only the image proxy). The fix might be a little too broad though, but I don't know for sure... I didn't see any mention of signatures, so maybe it's fine?

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
The cloudimg.io image is not the same from origin but lossy compress, does use self announced in jpeg IPTC comment metadata  `CREATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 91`
examples of the images from comment

https://heise.cloudimg.io/cdno/n/n/ 90.287 Bytes
original 114.314 Bytes

https://github.com/qsniyg/maxurl/commit/b136a3de1fbfd6597e3b9db19aaf25c305355fbf?diff=unified#diff-27f9d4a32bb1055d6e25712679ce34afR34448

**Comment by qsniyg** [comment]
Oops, thanks for letting me know, I should have checked [the documentation](https://docs.cloudimage.io/go/cloudimage-documentation/en/operations/cdn-cdno) before using `/cdno/` instead of `/cdn/` haha.

The `/cdn/` image matches the original image now :)

That being said, it will always try to go for the site first, before falling back to `/cdn/n/n/` if the site doesn't exist (e.g. if it's using an alias that the script doesn't recognize).

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
yes, cdNO sounds like no cdn. :)  
i can confirm, it is the original now.
checked by comparing file hashes of both origin server and cdn delivered. They matched.
