### ISSUE TITLE
Youtube keep opening the video in popup

### ISSUE THREAD

**Issue by Lucas559-noob** [qsniyg/maxurl#374]
Idk how to disable this on youtube, on home page(https://www.youtube.com) i can reproduce videos with mouseover enabled, I know if I hold shift it will ignore, but i want to disable, in configs in excludes i put https://youtube.com and https://www.youtube.com/watch* but no one work

**Comment by qsniyg** [comment]
Here's how I would do it:

 * Add `youtube.com` to the blacklist (it will blacklist anything under the domain youtube.com)
 * Enable `Apply blacklist for host websites` in order for the blacklist to not pop up when the host website is under the blacklist (otherwise, the blacklist will only be applied for the URLs within the popup, not the host website)

Alternatively, if you still want the thumbnails, but don't want the videos, add `googlevideo.com` to the blacklist instead (`Apply blacklist for host websites` would be unneeded in this case).

Hope this helps :)

**Comment by Lucas559-noob** [comment]
Ok it worked, thanks
