### ISSUE TITLE
Triggering download shortcut bypasses close behavior

### ISSUE THREAD

**Issue by lnp5131** [qsniyg/maxurl#410]
The close behavior no long applies when you trigger the download shortcut.

**Comment by lnp5131** [comment]
Another note to add is that this does not happen when it is set to any trigger released but only when all triggers are released.

**Comment by qsniyg** [comment]
Thank you for reporting!! It was a little hard to track down at first, but it turns out that any key will set it off (even rotation, flipping, etc.).

The reason is that it was checking if a keypress was part of the popup trigger key (which would then cancel the closing). The function that turns an event into a set of keypresses will also always contain the modifier keys, like Ctrl, Shift, and Alt, but it will set them to `false` if they're not pressed (which is useful for keyup events). Since Shift and Alt are part of the popup trigger key, it would always see them as being part of the keypress event, so it would always run that codepath if any key was pressed (which would cancel the closing).

It should be fixed now :)

**Comment by lnp5131** [comment]
Thanks for fixing it so quickly. That is an interesting interaction that can be easily missed. I look forward to contributing more as well.
