### ISSUE TITLE
No longer removing watermark w/ TikTok

### ISSUE THREAD

**Issue by schleeb** [qsniyg/maxurl#411]
This might not be fixable, but I know we used to be able to download the videos w/o the TikTok watermark/processing, but it's stopped working a month or so back.

**Comment by qsniyg** [comment]
So what happened here is that TikTok removed support for finding the video ID from the mp4 file, which afaik is the only way to find it without requiring the mobile API (which afaik cannot be accessed without special credentials, that cannot be derived from the web version)

As such, what I've done as an (admittedly terrible) workaround is add support for 3rd-party watermark removal sites (through the "TikTok: 3rd-party watermark removal" option).

But then of course, due to unrelated circumstances in the usa, many of them don't work anymore haha. IIRC snaptik, ssstiktok, and keeptiktok still work though, but they also happen to be the low-quality ones (576x* instead of 720x*), though this is almost certainly just a coincidence, as it's completely possible for them to return high-quality urls too.

Sorry, I know this isn't ideal. If someone discovers a way to find the video IDs from the web version, please send it my way and I'll add support for it in the script! :)

**Comment by schleeb** [comment]
I was afraid it was something like that :/
as always, appreciate the prompt response and the info!

**Comment by qsniyg** [comment]
It should work properly now for all configurations. If it doesn't, try enabling the app api (under Rules).
