### ISSUE TITLE
Mouse drag during key holds

### ISSUE THREAD

**Issue by lnp5131** [qsniyg/maxurl#415]
The popup would continuously attempt to load and then cancel while the key is being held if the mouse was dragged onto the image in specific circumstances. This occurs on Twitter and any time on first load of an image. The second situation it gets out of the loop once it is loaded, but the first situation does not. Possibly not registering that the popup is currently loading.

**Comment by qsniyg** [comment]
>if the mouse was dragged onto the image in specific circumstances

I'm not quite sure what you mean by this, sorry... would it be possible for you to share a screen recording, or screenshot or something of what you mean?

Also, just in case this is something relating to a specific configuration, could you export the settings (top button) and paste them e.g. to pastebin (or attach it here)?

**Comment by lnp5131** [comment]
There is also an additional problem that the popup does not initiate the close behavior when it loads after exiting the loop.

https://pastebin.com/raw/ccBmGWE8
![](https://i.imgur.com/BcoILRW.gif)

**Comment by qsniyg** [comment]
@lnp5131 For some reason the image fails to load here: 

![github_no_image](https://user-images.githubusercontent.com/20496822/91659037-e6146b00-ea81-11ea-9c41-3280150b0e1f.png)

Maybe try uploading to somewhere like Imgur?

Sorry, I'm still quite confused as to what the issue is...

**Comment by lnp5131** [comment]
I was trying to embed it but github might have reduced the maximum gif size below 5 MB

**Comment by qsniyg** [comment]
I'm trying to replicate the issue, but so far I can't replicate the issue shown in the gif you shared (I can replicate the close behavior issue though, so I'll fix that one soon), it works properly on my side...

Could you download the git version of the userscript (https://raw.githubusercontent.com/qsniyg/maxurl/master/userscript.user.js), replace `var _nir_debug_ = false;` with `var _nir_debug_ = true;` (near the top of the userscript). Then on twitter (make sure to reload in order for the new version to take effect), open the console, trigger the popup again (so that the issue is replicated), and once that's done, right click on the console, select "Save as", then upload the generated log here?

It should (hopefully) contain information to display what exactly the cause of the issue is...

**Comment by lnp5131** [comment]
Since the first issue I submitted that you fixed, I've been on the git version. I zipped it and sideloaded it into Firefox. I hope that the extension would be a superset of the userscript version. So far I can definitely confirm that the close behavior was fixed. 

https://pastebin.com/raw/ZRN1dkZW

It seems like "do_popup: check_image_get response:" returns a mixture of null and undefined and that cascades. It then resets and checks for the trigger key again. Perhaps that may help. I'm wondering if it is triggering on the element that the iframe that was generated for the popup and failing during the recursion loop.

**Comment by qsniyg** [comment]
@lnp5131 What appears to happen in the log is that it continually registers the "Control" key being pressed (22 times to be exact)...  I'm wondering if it's because your keyboard is faulty?

I've made a small test here: https://jsbin.com/luyuwezoye/edit?html,output , could you click on the "Output" section (right hand side), and hold down the control key? It should only increment the number once per press. If it continually updates the number, then the control key is being registered as being continually pressed.

Could you try binding the popup trigger key to something else, e.g. Shift+Alt+i, or some other key combinations, in case the control key on your keyboard is broken, but others work?

**Comment by lnp5131** [comment]
This was enlightening. Have you tried the test on your keyboard as well? Mine does increment continually, but it does so for every letter, shift, control, and alt. Could this be related?

https://stackoverflow.com/questions/6087959/prevent-javascript-keydown-event-from-being-handled-multiple-times-while-held-do

I made a small edit to account for the repeats here: https://jsbin.com/wusowomime/edit?html,console,output
This one increments by one per keypress for me.

**Comment by qsniyg** [comment]
Thank you for the research!! I've added the fix, let me know if it works :)

**Comment by lnp5131** [comment]
The problem with this fix is that when holding down the trigger key it would not trigger once the mouse hits the image. It may be an unintended feature but it is a feature that I've grown to like. It's similar to another extension. I think trigger key should be a trigger to enable mouseover which would be the inverse of the current mouseover implementation with a trigger key that prevents. Perhaps a couple booleans to prevent it from loading if it is currently loading, but to allow it to continuously scan as the mouse moves?

**Comment by qsniyg** [comment]
Good idea! Though I think a better way to implement that would be simply to repurpose the "Popup prevention key" to work as both an enabling or disabling key, depending on another setting. Would that work for you?

**Comment by lnp5131** [comment]
I just tried the mouseover function. There seems to be a set delay before each activation, which may be undesired.

http://jsfiddle.net/toragwu6/

This should be similar to what I am imagining at least. The mouseenter event may be useful in this case as it fires only once. In jsfiddle you would need to click run then click in the bottom right before you can interact with it.

**Comment by lnp5131** [comment]
I didn't see there was an option to set the delay my bad on that. This seems to be the ideal fix. There is a problem where if it is set to mouseover events that it does not do anything though.
