### ISSUE TITLE
Close behavior disabled during popup load

### ISSUE THREAD

**Issue by lnp5131** [qsniyg/maxurl#417]
If the key is released during popup load, the close behavior no longer works.

**Comment by qsniyg** [comment]
Thanks again for reporting!

From the configuration you sent, it looks like "Releasing triggers cancels loading" is disabled, which would cause the issue.

However, when "Don't close until mouse leaves" is enabled, it makes sense that there's another close behavior, which is the mouse leaving the image. So I've added a check so that it will consider the keyboard to be "good to close" if those circumstances are present, which allows it to work properly with your configuration :)
