### ISSUE TITLE
Mouseover event does not trigger with enable toggle

### ISSUE THREAD

**Issue by lnp5131** [qsniyg/maxurl#422]
"Use mouseover event" does not work with the new enable toggle. It does not trigger the popup. I'm also unsure of its current purpose however so I'm not sure what to look for.

**Comment by qsniyg** [comment]
Thanks for reporting! It should be fixed for Twitter now.

If that option is disabled, on every mousemove, it'll look for a new element to popup (with a delay set by the delay option). This option changes it to only work on mouseover events for known supported elements. This allows it to work a little more consistently with other image popup addons, as (as far as I know) they all work that way.

However, it also means that divs with `background-image`s aren't supported, as it only looks for mouseover events from image/video elements.

In this case, the issue was caused because twitter uses a structure like this:

```
<div style="background-image: url(https://pbs.twimg.com/...)" />
<img src="https://pbs.twimg.com/..." style="opacity: 0" />
```

It registered a mouseover event on the image, but then discovered that the image had an opacity of 0, and therefore decided not to pop up for it. However, what is visible to the user is actually the div above it. The regular method (using mousemove and elementsFromPoint) supports this though, so the fix was just to use the regular method (using elementsFromPoint), without using the mousemove handler.

I should probably add an option to configure it though, as it might be desirable (for either performance or compatibility reasons) to just use the element provided by the mouseover event.
