### ISSUE TITLE
NSFW: Gelbooru shows popup but without an image

### ISSUE THREAD

**Issue by lnp5131** [qsniyg/maxurl#430]
For any image on the site, it shows a popup without an image. It also ignores the zoom keys. I know in the past that Gelbooru actively fights against any userscript interacting with their site in particular with image scraping. 

Here's my current config: https://pastebin.com/raw/6xD74w2M

I swapped most of the configs to test if any of them were causing the issue but it seems like all the ones I tested resulted in no image. Also, from the console, it is pulling the right image link. Other boorus do not have this issue from what I gathered.

**Comment by qsniyg** [comment]
This is actually due to adblock (as is almost always the case unfortunately haha). It injects these styles:

`a[target="_blank"] > img { display: none !important; }`

and:

```
div[style*="padding: 10px;"][style*="dashed #333;"],
a[href*="/track/"], .thumbnail-preview + center > style + div,
.content > a[rel="nofollow"] > img,
.contain-push > .hidden-xs,
a[target="_blank"] > div,
a[target="_blank"] > img,
[xtzwt83n5] {
    display: none !important;
}
```

A temporary workaround is to disable "Link images", which, if [the linked commit](https://github.com/qsniyg/maxurl/commit/0eed42c5f9f34da9cfc274422375f0e6435d2ebc) is applied, will prevent the link from adding the `target="_blank"` attribute.

A better solution is definitely needed though, I'm thinking of doing the same trick as I did for pornhub, where it loops around various tricks to try to find one where the image is visible. In this case, probably something like `a[target="_blank"] > span > img`. Of course, this is still a cat and mouse game, though at least we're not the one in the crosshairs, we're just accidentally implicated.

**Comment by lnp5131** [comment]
Perhaps apply that fix as a fallback if the popup image is not visible? I'm thinking another way to get around this is to generate the popup elements with `display: block !important` as an inline style or something that would take precedence.

**Comment by qsniyg** [comment]
>Perhaps apply that fix as a fallback if the popup image is not visible?

Exactly yeah :) That's what I did for pornhub

>I'm thinking another way to get around this is to generate the popup elements with display: block !important as an inline style or something that would take precedence.

It already does set it as `!important`, I don't think there's any way to override adblock's styles though, unfortunately :(

**Comment by lnp5131** [comment]
What I mean is to apply it generically as a fallback in case it happens again unless that might cause a regression. I wonder if we could bypass the block with a function.

```
$(document).on('click', a, function(e){ 
    e.preventDefault(); 
    var url = $(this).attr('href'); 
    window.open(url, '_blank');
});
```
[Source](https://stackoverflow.com/questions/35601258/target-blank-does-not-open-a-new-tab)

**Comment by qsniyg** [comment]
(I ended up replying to your comment in [another issue](https://github.com/qsniyg/maxurl/issues/435#issuecomment-687704521) )

Another solution could be to go all google and create custom randomly-generated elements, like this:

```
<a href=...><abcdefg><img ... /></abcdefg></a>
```

That way, adblockers can't really bypass it, though it might add a fingerprinting risk (so it should be optional). I'm not sure what browser support for that is like though.

**Comment by lnp5131** [comment]
[](https://caniuse.com/#feat=custom-elementsv1)

It seems a majority of major browsers do support it or at least partially. (92.93% for full + partial support) This seems like a pretty good option as a permanent solution. The ones that don't support it are specialty or old browsers.

**Comment by qsniyg** [comment]
(I've been using MDN, but that site's clearly much better for browser support, thanks for linking!)

Interesting... I wonder though if it's referring to the ability to have the browser recognize custom elements (through the `customElements` global), or just the ability for the browser to render content from random tags, because I only need the latter. I'll try downloading a really old firefox version (and hope it still runs...), and see if it works, because iirc I did get something like that working in something like the firefox 3-4 days.

**Comment by lnp5131** [comment]
They might treat custom elements as a regular div and take the corresponding rules as to take care of the extraneous cases in their lexical analyzer. It seems like from your comment in the other issue mentions that `window.open` is commonly blocked. I don't think there are many widely applicable approaches to opening a new tab or new window while consider adblockers. The custom elements would be unreasonable for them to block so it may be worth prioritizing over the other alternatives.

**Comment by qsniyg** [comment]
>The custom elements would be unreasonable for them to block so it may be worth prioritizing over the other alternatives

I agree, and in any case, we're not directly fighting against adblockers, we're just trying not to get stuck in the crossfire :)

I'll add it as an option anyway, in case it does break something though
