### ISSUE TITLE
facebook.com

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#438]
Image in https://www.facebook.com/idolmastermlTD.ch/posts/2711191972484165

Image url: 
`https://scontent-dfw5-2.xx.fbcdn.net/v/t1.0-0/p526x296/118399407_2711229069147122_290006567631034732_o.jpg?_nc_sid=730e14&_nc_ohc=9P-9mkgmUtEAX8CArDo&_nc_ht=scontent-dfw5-2.xx&tp=6&oh=f51475ad4c1c4100a8b23902b02b1662&oe=5F7C9957`

Bigger/orig image (can be obtained by click on the image first): 
`https://scontent-dfw5-2.xx.fbcdn.net/v/t1.0-9/118399407_2711229069147122_290006567631034732_o.jpg?_nc_sid=730e14&_nc_ohc=9P-9mkgmUtEAX8CArDo&_nc_ht=scontent-dfw5-2.xx&oh=b22f007c618ecb76e62f5ae4202c220a&oe=5F79EF09`

Not sure if it is trivial to get it, though.

**Comment by fireattack** [comment]
Sorry, I just saw #211. If it's covered there already feel free to close this!

**Comment by qsniyg** [comment]
Working on it! https://github.com/qsniyg/maxurl/issues/211 :)

(ah, you just noticed it too haha)

**Comment by qsniyg** [comment]
It's mostly done already, all that's left is just to implement proper album support, support for non-logged in posts, and support it as a host rule (rather than just a pagelink rule) :)

**Comment by fireattack** [comment]
"Most" indeed, I suppose, lol. Thanks for the hard work as always!

**Comment by qsniyg** [comment]
Hahaha true it sounds like a lot when I put it that way. But it's actually not much at all (esp. with the newly rewritten album support), the hardest part was actually parsing the webpage to find the images (especially with their previous system which is iirc now deprecated, had to implement a custom json parser in order to be able to actually parse it).
