### ISSUE TITLE
Commit c7591cc broke multi-page pixiv entries

### ISSUE THREAD

**Issue by kattjevfel** [qsniyg/maxurl#464]
Did some bisecting and c7591cc29483eca1c352036990b7917ae24c2c4f breaks any pixiv entry with more than 1 page, any other page will be redirected to _p0.xxx (first page) non-stop and you'll have to fight the plugin to view the other pages.

Firefox 81.0.1, browser plugin.

EDIT: Realised I should perhaps provide an example, here: https://www.pixiv.net/en/artworks/84777803

**Comment by qsniyg** [comment]
Thank you!! I'm not quite sure how that commit would have broken it, but it might have unearthed the real cause, which is that I migrated Pixiv to a pagelink rule (i.e. the rule "redirects" to https://www.pixiv.net/en/artworks/84777803, which is then handled by a rule that specifically handles that url), without knowing that multi-page Pixiv entries even existed haha. The fix was basically just to add a `#imu-page=...` at the end, so it knows which one to return.

That being said, there's some really weird issue where the returned object retains all of the history of previous times it was run. It shouldn't affect any actual use case (unless you're browsing through the same gallery thousands of times without reloading I guess), but I'll see if I can fix it.
