### ISSUE TITLE
several new domains

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#480]
### `images.fastcompany.net`
initial: https://images.fastcompany.net/image/upload/w_937,c_limit,f_auto,q_auto,fl_lossy/wp-cms/uploads/2019/06/5-inside-silicon-valleys-new-robot-run-farm-813x457.jpg
current: https://images.fastcompany.net/image/upload/wp-cms/uploads/2019/06/5-inside-silicon-valleys-new-robot-run-farm-813x457.jpg
should: https://images.fastcompany.net/image/upload/wp-cms/uploads/2019/06/5-inside-silicon-valleys-new-robot-run-farm.jpg

### `cdn\d+.allafrica.com`
from: https://allafrica.com/view/group/main/main/id/00075054.html
img: https://cdn04.allafrica.com/download/pic/main/main/csiid/00570148:ed06278f4617fca6d5e004136f6b4fc6:arc614x376:w614:us1.jpg

### `blog.adobe.com`
from: https://blog.adobe.com/en/2020/09/23/adobe-unveils-ambitious-multi-year-vision-for-pdf-introduces-liquid-mode.html
img: https://blog.adobe.com/hlx_da4186554b4266692a126e34487444d6f7884263.jpeg?width=1500&auto=webp

### `assets.cdn.moviepilot.de`
from: https://www.moviepilot.de/serie/outcast
img: https://assets.cdn.moviepilot.de/files/8de5e54a58722dabbde414ce6eb7f7468eb69ce3b6aabd4879b5756039d2/limit/500/1000/outcast-poster-01.jpg

**Comment by qsniyg** [comment]
Thank you very much!!

Everything should be fixed/supported now. The `moviepilot.de` one was actually properly supported, but wasn't redirected due to the HEAD request returning an invalid content-length header. I usually miss these because the browser caches the GET headers if accessed, so I don't actually see an issue until I try a new URL.
