### ISSUE TITLE
update wapo

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#482]
## 1.

```
https://www.washingtonpost.com/resizer/5i6h3byfAbADvdFUAn-5RMklGQ4=/1200x630/filters:focal(2231x1260:4531x2559):quality(100)/arc-anglerfish-washpost-prod-washpost/public/JBWJ3HR4RQI6VL7CBEHLG63AWE.jpg
https://www.washingtonpost.com/resizer/Heq_MXyYFkN5Knz0ImwQ3QmaPGQ=/arc-anglerfish-washpost-prod-washpost/public/W5HKYCWPJJF6XBNGTRCZHXZ4EU.jpg
```

should go to

```
https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/JBWJ3HR4RQI6VL7CBEHLG63AWE.jpg
https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/W5HKYCWPJJF6XBNGTRCZHXZ4EU.jpg
```

## 2. fix bug
```
https://img.washingtonpost.com/wp-apps/imrs.php?src=https://www.washingtonpost.com/rf/image_982w/2010-2019/WashingtonPost/2020/03/14/Health-Environment-Science/Graphics/promo2-coronavirus-simulator-0313.jpg&w=60&h=60
```

is currently redirecting to
```
https://img.washingtonpost.com/wp-apps/imrs.php
```

it should go to
```
https://www.washingtonpost.com/rf/image_982w/2010-2019/WashingtonPost/2020/03/14/Health-Environment-Science/Graphics/promo2-coronavirus-simulator-0313.jpg
```

This might be a good time to take care of the fixme 😉 https://github.com/qsniyg/maxurl/commit/c6a89953dcbcc8060a0d1f56bfefa618814817c4#diff-1bc842c9e7dda2f26048e68021e82a3c290fb38639d0acf259392b26f4664fc8R80966

**Comment by qsniyg** [comment]
Thanks as always!!

Regarding #2, I'm not quite sure how it worked before. I probably added removing `[?#].*` to the `/rf/` rule sometime after... in any case, the fix was just to move the rule above the rf one. A better fix I guess would be to make the rule more specific, but for now it should work :)

About the fixme, already done! https://github.com/qsniyg/maxurl/commit/73594d5473b27e8a3a2ae6a8b812c7b2266cffcd :)
