### ISSUE TITLE
Support theblast

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#485]
`https://theblast.com/`

```
https://img.srgcdn.com/e/w:1000/RERrSzVLbHhPOWhHVkZBa05hcjIucG5n.jpg
https://img.srgcdn.com/e/h:626/VTI0WVY4dXh6UW5zbkxYS1lHVHUuanBn.jpg
https://img.srgcdn.com/e/w:750/a2k5aWVsaVdJaktoZHhXYUJxNXYuanBn.jpg
```

to

```
https://img.srgcdn.com/e/RERrSzVLbHhPOWhHVkZBa05hcjIucG5n.jpg
https://img.srgcdn.com/e/VTI0WVY4dXh6UW5zbkxYS1lHVHUuanBn.jpg
https://img.srgcdn.com/e/a2k5aWVsaVdJaktoZHhXYUJxNXYuanBn.jpg
```

**Comment by qsniyg** [comment]
Fixed by https://github.com/qsniyg/maxurl/commit/01a6ecbc04e518a705fec2944f519778fa8b9ba1

Thank you as usual!! Interesting, the filename is actually base64-encoded:

`RERrSzVLbHhPOWhHVkZBa05hcjIucG5n` = `DDkK5KlxO9hGVFAkNar2.png`
`VTI0WVY4dXh6UW5zbkxYS1lHVHUuanBn` = `U24YV8uxzQnsnLXKYGTu.jpg`
`a2k5aWVsaVdJaktoZHhXYUJxNXYuanBn` = `ki9ieliWIjKhdxWaBq5v.jpg`

I'll have to see if the direct filenames are accessible somewhere...

**Comment by llacb47** [comment]
Originals:

```
https://storage.googleapis.com/dystribute-media/DDkK5KlxO9hGVFAkNar2.png
https://storage.googleapis.com/dystribute-media/U24YV8uxzQnsnLXKYGTu.jpg
https://storage.googleapis.com/dystribute-media/ki9ieliWIjKhdxWaBq5v.jpg
```

**Comment by qsniyg** [comment]
You're a legend!! :D
