### ISSUE TITLE
xcdn.next.co.uk

### ISSUE THREAD

**Issue by keophcp** [qsniyg/maxurl#487]
small: https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemShot/315x472/306253s.jpg
large: https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/AltItemZoom/306253s.jpg

**Comment by qsniyg** [comment]
Thank you!!

This one turned out to be a little challenging, though many online stores tend to be rather... poorly designed from an image storage standpoint (no consistent way to access images).

Interestingly, you can remove the watermark for search results, which also returns the (presumably) original version:

`https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/676/R51707.jpg`

to:

`https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/NoBrand/Search/R51707.jpg` (same size)

However, this actually changes certain images:

`https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/Search/676/912209.jpg`

to:

`https://xcdn.next.co.uk/Common/Items/Default/Default/ItemImages/NoBrand/Search/912209.jpg` (note 1800x2700)

Maybe I should add this under the "possibly different" problem...
