### ISSUE TITLE
underarmour, scene7

### ISSUE THREAD

**Issue by keophcp** [qsniyg/maxurl#488]
small: https://underarmour.scene7.com/is/image/Underarmour/PS1351722-002_HF?rp=standard-0pad|gridTileDesktop&scl=1&fmt=jpg&qlt=50&resMode=sharp2&cache=on,on&bgc=F0F0F0&wid=512&hei=640&size=512,640
thought it will be original, but still small, even smaller: https://underarmour.scene7.com/is/image/Underarmour/PS1351722-002_HF
can't figure out rule for this one, although larger images exist, but complicated url

**Comment by qsniyg** [comment]
Thank you!!

I had actually supported that one a long time ago, but it would redirect to broken images rather often, so I had to disable it. Since then though, I've added a `bad_if` property, which allows it to avoid redirecting to images that are likely to be broken, so this rule can be enabled again! :)
