### ISSUE TITLE
Improve twitter rule

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#545]
`https://pbs.twimg.com/media/EnlTOuPVkAEVFcG?format=jpg&name=900x900` should redirect to `https://pbs.twimg.com/media/EnlTOuPVkAEVFcG?format=jpg&name=medium`

`https://pbs.twimg.com/media/EnlTOuPVkAEVFcG.jpg?name=medium` is 404

Perhaps the userscript should check the `?format=jpg&name=whatever` urls as well as the `.jpg?name=whatever` urls?

See https://github.com/mikf/gallery-dl/issues/1145

**Comment by qsniyg** [comment]
Thanks for reporting! I decided to take the opportunity to improve the twitter rule a bit as well. As someone else noted in the issue, it does appear like twitter's trying to phase out the `.jpg` and instead go for `format=jpg`, so I decided to just automatically go in that direction, rather than double the amount of queries (there can already be an absurd amount of queries for tweet images, especially for images like that where `medium` is the largest size available).

To avoid the `.jpeg` issue when saving, I set it to have a custom filename, replacing jpeg with jpg.
