### ISSUE TITLE
add quizlet google image proxy

### ISSUE THREAD

**Issue by llacb47** [qsniyg/maxurl#549]
`gimg.quizlet.com` is used by quizlet for profile pictures of user accounts that login with google oauth.

```
https://gimg.quizlet.com/a-/AOh14GgY786zMOL8uFswlEBNT3kyqGM2Zmi57PEp9lxwiQ?sz=48
https://gimg.quizlet.com/-kQudKumKZVc/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucmfoxWZRRGdjq07juSAXKtKuZ_uow/photo.jpg?sz=48
https://gimg.quizlet.com/a-/AOh14GgMqQYnhmbKr94I6XZNto0r2ZTZ1md7lz0hpICmBw=s96-c?sz=48
https://gimg.quizlet.com/a-/AOh14GjkJ7PECItpFbj1_vNUR6tPEs7Rv-Eu8far92A8=s96-c?sz=48
https://gimg.quizlet.com/a-/AOh14Gj4vniFQ6t0uvOMd3uipvyy4hMazk3nNqVb1C_D=s96-c?sz=24
https://gimg.quizlet.com/-YU-C4l8AAU8/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuclAhqEyzYJwgRfjbeCKmDxni2Xd4w/photo.jpg?sz=24
```

just replace `gimg.quizlet.com` with `lh{3,4,5}.googleusercontent.com`

**Comment by qsniyg** [comment]
Thank you!! I'm not sure if this is too strict, but from the urls you provided (and from the few example ones in the script), it seems like /a-/ and /-.../ seem to be the first folders, so that's how it detect whether or not to change it. If this doesn't support all, perhaps it might be an idea to just replace the domains without any checks, I'm not sure...
