### ISSUE TITLE
Organize options page

### ISSUE THREAD

**Issue by rEnr3n** [qsniyg/maxurl#553]
Currently, all the options are laid on one page. Scrolling through the options can be difficult. Lots of text make it difficult to read through the options. I have two requests.

1. Put the option categories (General, Redirection, Popup, etc.) to separate tabs.
1. Move all option description to tooltips.

**Comment by qsniyg** [comment]
Actually, both are already possible! :)

Enable: Settings -> Use tabs
Disable: Settings -> Description below options

**Comment by rEnr3n** [comment]
Can it be set as default? My eyes failed me for some reason. I'll guess it's due to the overwhelming amount of text.

**Comment by qsniyg** [comment]
Yeah I was thinking about that once I wrote that comment. I agree that tabs should be default (the main reason it wasn't is because I was still testing it, I didn't want to impose a potentially broken feature), but imo the description one should remain enabled by default, because it does contain a fair amount of information about what the options do.
