### ISSUE TITLE
imagefapusercontent & fap.to as 3rd party

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#557]
Many websites host images that are broken and I noticed always from exactly these two servers.
When broken image is open in new tab server is fap.to and it says 404 not found
When broken image link is open in new tab server is *.imagefapusercontent.com and it says "need the real thing? visit imagefap.com"
I noticed this on at least 10 porn websites in last few years. Such images appear in google image search but looks like only cached versions.
Example: https://www.wifeporn.de/Gallery/8345235/Amateur-Bigfoot-Porn
I remember seeing one extension for firefox that fixed that, but I think it was in old firefox store, now in classic addons archive.

**Comment by qsniyg** [comment]
Thanks for reporting, I've updated the imagefap rules. For imagefapusercontent, it should automatically redirect to the working version, without any intervention. For fap.to, since it's an HTML page, I've added a feature to enable redirecting for HTML pages too. I'd recommend leaving it disabled by default however, as it'll redirect a good portion of websites to images/videos.

You can also use Replace Images on the host page, which should replace them to working versions :)
