### ISSUE TITLE
auto rename images

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#565]
Extensions that download pictures from instagram like:
https://addons.mozilla.org/en-US/firefox/addon/media-helper/
https://chrome.google.com/webstore/detail/downloader-for-instagram/olkpikmlhoaojbbmmpejnimiglejmboe

automatically rename images according to username (profile), while some apps for pc and mobile like 4kstogram and various android downloaders rename them according to post url, for example this photo:
https://scontent-ams4-1.cdninstagram.com/v/t51.2885-15/e35/130310034_217807986414619_3871902471875447330_n.jpg?_nc_ht=scontent-ams4-1.cdninstagram.com&_nc_cat=107&_nc_ohc=nQ-5VcviitAAX-Juhvf&tp=1&oh=601b3b8bcdc793b02957e56bc93b9f83&oe=5FFC10C7¸

ref: https://www.instagram.com/p/CIfThMRjpUu/

is having name 130310034_217807986414619_3871902471875447330_n.jpg but gets renamed to lim_friendship_130310034_217807986414619_3871902471875447330_n.jpg

and if I remember correctly to CIfThMRjpUu.jpg and few similar names

Can you make that at least in case when images are downloaded via your extension directly? At least for famous websites like IG, FB, Twitter....at least if extension is used while we are on username page?

**Comment by qsniyg** [comment]
Good idea!! I've added preliminary support for IG here: https://github.com/qsniyg/maxurl/commit/fb53c8dbd803aa9ec1daf30af0f5f6be96c07f95

That said, the proper solution would likely be something like #409. The idea would be that you could specify it as something like:

`%username_%filename`

or perhaps:

`(%iso_date) %username %filename` (e.g. `(2020-12-12T10:20:30) instagram 1234567_....jpg`)

As for FB... facebook support needs to be properly implemented first, which is going to be a fair bit of a challenge, due to the fact that it's very difficult to get the post ID from it.

**Comment by qsniyg** [comment]
Everything should be implemented now (including #409), with the exception of FB as I mentioned earlier :)

**Comment by GoblinLegislator** [comment]
Why does this no longer work?

**Comment by qsniyg** [comment]
@GoblinLegislator I made a _really_ stupid typo, setting the values back to the info object, rather than to the format object. Fixed, thanks for reporting!!
