### ISSUE TITLE
donnemetropolitane

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#575]
small: https://www.donnemetropolitane.it/shop/22302-home_default/leggings-stampato-deanna.jpg
small: https://www.donnemetropolitane.it/shop/22302-thickbox_default/leggings-stampato-deanna.jpg
large: https://www.donnemetropolitane.it/shop/22302-large_default/leggings-stampato-deanna.jpg
large: https://www.donnemetropolitane.it/shop/22302/leggings-stampato-deanna.jpg

**Comment by qsniyg** [comment]
Thank you! Another of those prestashop sites... Been thinking for a while I should find _some_ way to make it generic, but I don't know how to do that without making it overly generic and possibly breaking other sites. Also, this is the first time I've seen it being used in a subfolder (`/shop/`), instead of directly on the domain, so I guess it would require exceptions anyways.
