### ISSUE TITLE
brazzers

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#576]
http://static-vz.brazzerscontent.com/scenes/2409998/975x548.jpg
http://static-vz.brazzerscontent.com/scenes/9087/br2.jpg
http://static-vz.brazzerscontent.com/scenes/9087/preview/thm/12.jpg
http://static-vz.brazzerscontent.com/scenes/9087/preview/img/12.jpg
Don't know if smaller or higher resolutions exist for 1st one, and is 2nd vs 3rd and 4th some pattern or accidentally same image because other numbers did not work. But no redirects happened in any case from extension.

**Comment by qsniyg** [comment]
Thank you! For the first one, I don't know if there's a larger one either, but since it's a thumbnail of the video, I figured it might as well just redirect to the video (which can be configured by disabling various video options or by using the blacklist, and the upcoming #573 one should provide something proper without needing to change global options).

The second appears to be an album thumbnail, so I'm not really sure if anything can be done about that easily, as I don't know if it's possible to know which preview image it refers to (if it refers to any of them). Interestingly, that one appears to be one of the only albums with more than 5 images, perhaps because it's older (and at one point, they supported more thumbnails)? In fact if you look at the source, only up to the 5th image is even made publicly available, which is interesting. That being said, the original page hosting the video should be printed in the console (or if you open it through the popup).

And of course the thm->img rule is added too :)
