### ISSUE TITLE
avaz.ba

### ISSUE THREAD

**Issue by nijaz-lab** [qsniyg/maxurl#579]
This is most famous newspaper in Bosnia, similar to Klix.ba

old photos large: https://avaz.ba/media/old/57499b1e-f71c-483d-a158-1a220a0a0a64-ena-saric4.JPG
old photos large: https://avaz.ba/media/old/571a8c9c-3688-4932-8373-0e030a0a0a64-almir-badnjevic.JPG
old photos large: https://avaz.ba/media/old/58724ed7-dd5c-4b27-acb7-7b820a0a0a64-kopaci-3.JPG

large: https://avaz.ba/media/2020/10/03/1347170/thumbs/cover_big.jpg

largest thumb: https://avaz.ba/media/2020/12/17/1395333/thumbs/873x400.jpg
bit smaller thumb: https://avaz.ba/media/2020/12/17/1395334/thumbs/w873.jpg
small thumb: https://avaz.ba/media/2020/12/17/1395333/thumbs/240x225.jpg

https://avaz.ba/media/2020/12/15/1394018/thumbs/800x450.jpg

old thumbs, maybe largest: https://avaz.ba/media/2020/12/16/1394867/thumbs/800x450.jpg
actually looks like that is largest thumbs, other links work with that resolution too

Also there are subdomains:

https://sport.avaz.ba/media/2020/12/17/1395290/thumbs/240x225.jpg
https://sport.avaz.ba/media/2020/03/27/1212742/thumbs/873x400.jpg

larger thumb: https://sport.avaz.ba/media/2019/10/21/1083827/thumbs/1005x635.jpg

Other subdomains:
https://bebe.avaz.ba/
https://zdravlje.avaz.ba/
http://kuharica.avaz.ba/

And maybe more.

**Comment by qsniyg** [comment]
Unfortunately, I'm not sure if this one is possible to support (at least for original images). For instance:

```
https://sport.avaz.ba/media/2019/07/19/1001528/thumbs/873x400.jpg -- thumb
https://sport.avaz.ba/media/2019/07/19/1001528/italija-bih101.jpg -- original

https://sport.avaz.ba/media/2019/04/13/911252/thumbs/873x400.jpg -- thumb
https://sport.avaz.ba/media/2019/04/13/911252/barca.jpg -- original

https://avaz.ba/media/2017/11/07/402692/thumbs/873x400.jpg -- thumb
https://avaz.ba/media/2017/11/07/402692/adzem-1.jpg -- original

https://sport.avaz.ba/media/2019/02/27/864566/thumbs/873x400.jpg -- thumb
https://sport.avaz.ba/media/2019/02/27/864566/vranjes-bih-estonija-44.JPG -- original, note the uppercase JPG, this likely means that it's the original filename being stored
```

There doesn't appear to be any way to find the original image from the thumbnail, and many of the thumbnail filenames (like `800x450.jpg` fail to work for some of the images). My guess is that it's just serving static files that were automatically generated (though if you go to the folders, like `/thumbs/`, it returns 500 instead of 403, which _maybe_ indicates it's dynamic to some degree -- though it's also returned for _any_ invalid filename).

There also doesn't appear to be any way to find the original images from the pages themselves. The original images I found were through an `inurl` google search, not through the website itself.

Not all links work with the `800x450.jpg` filename though, for instance: https://avaz.ba/media/2020/12/17/1395333/thumbs/800x450.jpg

Additionally, the thumbs don't always work as one would expect (all found from google):

```
https://avaz.ba/media/2018/04/04/562555/thumbs/800x450.jpg -- 1480x720
https://avaz.ba/media/2019/04/25/923684/thumbs/w873.jpg -- 738x1312 (perhaps the image is not as wide as 873? but it does look upscaled)
https://avaz.ba/media/2018/01/03/465354/thumbs/w873.jpg -- 738x1312 (definitely upscaled)
https://avaz.ba/media/2020/03/23/1209096/thumbs/w873.jpg -- 737x1284 (highly upscaled, off-by-one from the one above for the width)
https://avaz.ba/media/2019/04/21/919943/thumbs/w873.jpg -- 737x1357 (same)
https://avaz.ba/media/2018/02/07/500662/thumbs/800x450.jpg -- 1280x720 (looks either upscaled or really heavily compressed)
```

Additionally, the one you linked of w873: `https://avaz.ba/media/2020/12/17/1395334/thumbs/w873.jpg` is also 738x500, so I'm guessing it's a typo in their thumbnail generation script.

It seems to me that there's no way to find an original image, and going for larger thumbnails is often going to result in upscaled images. I _can_ add support for this if you want, but it would require "Possibly upscaled images" to be enabled.

As for `/old/`, I didn't find much related to being able to find larger images. Seems like it's just storing an image as a uuid (the `hex-hex-hex-hex-hex` prefix), then adding the filename after. The closest I was able to find to something relating an automatically generated filename was:

`https://avaz.ba/media/old/560a7354-ad30-455f-a522-3b7c0a0a0a64-28deport-1443307557057-articlelarge.jpg`

But I think this was just the filename, admittedly I didn't try that many combinations, but every time resulted in 404.

I'll leave this open though, in case a method for finding the original image is found. It may be unlikely, but it's happened in the past...

**Comment by nijaz-lab** [comment]
Well those large ones are old anyways, probably not used anymore. Can you add rule at least for thumbs, to check if it exists and only redirect if it does, since most of them exist, for new news at least. Maybe try at least for 2 or 3 most common and largest resolutions.

**Comment by qsniyg** [comment]
Alright, I'll add it in a bit :)

In the meantime, here are some other resolutions:

`https://avaz.ba/media/2018/07/13/650140/thumbs/h550.jpg`

`https://avaz.ba/media/2018/01/06/468200/thumbs/1200x700.jpg`

**Comment by nijaz-lab** [comment]
One more link:
https://avaz.ba/media/2020/12/20/1397496/thumbs/cover_small.jpg
https://avaz.ba/media/2020/12/20/1397496/thumbs/cover_big.jpg

**Comment by qsniyg** [comment]
Thanks, and sorry for getting back so late. I've kind of supported it as much as I could, but it's quite awful. If there are any images made smaller, please let me know. It uses `find_actual_largest_image` to try to find which image is largest through http requests (just checking the content-length header for the moment), but this could theoretically lead to upscaled cropped images being used over originally-sized images.

For it to work, "Possibly upscaled images" under Rules needs to be enabled.
