### ISSUE TITLE
stfucdn.com

### ISSUE THREAD

**Issue by DirtyGoblinLegislator** [qsniyg/maxurl#585]
https://static-td-a.stfucdn.com/albums/main/400x400/22000/22390/268575.jpg?ttl=1608842674&token=46ad1e294d2132b11b6efc18055546b5

https://static-td-a.stfucdn.com/albums/sources/22000/22390/268575.jpg?ttl=1608842699&token=4ed8e395bff69c71d388d7dadd041ace

**Comment by qsniyg** [comment]
Thank you!

Consider me surprised that this is actually somehow possible. Turns out the token (/signature) isn't actually necessary at all, and it works without changing it. I thought it would either be impossible, or would require somehow finding the page url from the image url (or only work as a host rule... i.e. it would only work if one were to open the popup on thee site itself).

I've also added support for videos, as it uses that same system most other sites tend to use.
