### ISSUE TITLE
Add imgblaze_net support

### ISSUE THREAD

**Issue by elvisef** [qsniyg/maxurl#612]
Original link: `http://imgblaze.net/fthtmx5d`

The big size image is `https://www.fiyar.live/data_server_new/2899/small/small_206_1000(9).jpg` - hosting seems familiar.
I think this should be a quick addition-fix.

Will You look into it ? : )

**Comment by qsniyg** [comment]
See if https://github.com/qsniyg/maxurl/commit/88336de1b3de47c6065701408d73262476c6e1fb fixes it.

If not, would it be possible to share the html code that hosts the thumbnail image?

**Comment by elvisef** [comment]
Doesn't work, because now it redirects me to: `http://imgair.net/fthtmx5d`
A big sized image is now: `https://prcf.fiyar.live/data_server_new/2899/big/206_1000(9).jpg`

**Comment by qsniyg** [comment]
I've added support for it: https://github.com/qsniyg/maxurl/commit/f465ef0ae6951c2e75ec2cc3da61ebe4d49721cc

I'm not exactly sure how you're trying to access the image though. Is it through the imgair link itself (i.e. the link to the html page)? If so, make sure that "popup for plain hyperlinks" is enabled.

**Comment by elvisef** [comment]
I have a page with many thumbnails.
One of them is: `http://imgblaze.net/fthtmx5d`
So I use it, by clicking on it.
When I click it, it redirects me to `http://imgair.net/fthtmx5d` (firstly it was another link I mentioned in my first post, now it changed).

As I have "HandyImage" addon installed it shows me the direct big sized image, so I know that the image is `https://prcf.fiyar.live/data_server_new/2899/big/206_1000(9).jpg` (earlier it was another link - this one: https://www.fiyar.live/data_server_new/2899/small/small_206_1000(9).jpg).

I think their page have some capabilities to change links in order to block robots or something. Some links are changing but redirecting to the same images. Very interesting.

The "HandyImage" is not important now, I can disable it but What I do is  just run "replace images" with MaxUrl on page with many "imgblaze.net" links. Links from "imgblaze.net" are not replaced, that;s why I am writing : )

I've tested it on new clean FF profile with maxUrl only.

**Comment by qsniyg** [comment]
>What I do is just run "replace images" with MaxUrl on page with many "imgblaze.net" links

Are they only links, or are they linked images? If they're only links, then I'll have to add an option for that (the "Replace links" option iirc doesn't do this, it only replaces the links for linked media, but not pure links - i.e. a plain text hyperlink).

If they're linked images, can you send a snippet of the html code that stores them?

**Comment by elvisef** [comment]
The source looks like this:
`<a href="http://imgblaze.net/fthtmx5d" target="_blank"><img src="http://imgblaze.net/data_server_new/2899/small/small_206_1000(9).jpg" alt="" border="0"></a>`

**Comment by qsniyg** [comment]
Should be fixed with https://github.com/qsniyg/maxurl/commit/3b769f688ef62bc65a697ab7ce48273cd8b7320e :)

By the way, would it be possible in the future to avoid sending nsfw imagery if possible? I try to avoid adding links to nsfw images to the script.

Thank you for your reports and contributions, I really appreciate you taking the time to submit these! :)

**Comment by elvisef** [comment]
It works, thanks ! : )

Anyway, what is "nsfw" ? You mean this: `https://www.howtogeek.com/438957/what-does-nsfw-mean-and-how-do-you-use-it/` ?

If yes, alright I will do my best of course. Most links from less known image servers are probably just "nsfw". So eventually I will try to locate other "non-nsfw" images to show the problem with replacing images.

But generally You are not adding links to images, but to image hosting, right ? Or maybe You think about adding any nsfw links to the github issue comments ? : ) Let me know I am right.

**Comment by qsniyg** [comment]
>Anyway, what is "nsfw" ? You mean this: https://www.howtogeek.com/438957/what-does-nsfw-mean-and-how-do-you-use-it/ ?

Sorry, yes, porn basically :)

The way I tend to find images is by searching `inurl:website.com` through google images (or startpage if you prefer), you'll usually be able to find some examples there.

>But generally You are not adding links to images, but to image hosting, right ?

Correct, but whenever possible, I like to add test links, in case I have to modify the rule. That way I can test to ensure the new rule doesn't break other links (something which has saved me a few more times than I'd like to admit...).

>Or maybe You think about adding any nsfw links to the github issue comments ?

Yes, if you could adding nsfw links to github issues, I would really appreciate it, thank you! It makes my job much easier :) It also avoids possible problems for others browsing the repository (due to e.g. work, or living in a country that doesn't allow it).

Feel free to [contact me](https://qsniyg.github.io/) if you have any trouble though (Matrix might also make some of the back-and-forth replies quicker).
