### ISSUE TITLE
0.16.0 completely broken with waterfox classic

### ISSUE THREAD

**Issue by snottyone** [qsniyg/maxurl#618]
for both addon and userscript version, functionality gone, options page doesn't load
i reinstalled 0.15.1, works again

**Comment by qsniyg** [comment]
I can reproduce it, thank you! Seems to be the same issue as #616 (couldn't reproduce it because I was using a very recent firefox version, so thanks for letting me know that it failed under waterfox!)

Turns out it's because I used a feature only available in very recent javascript versions (named capture groups). Will try to find a way to fix, as compatibility with older browsers has always been a priority for this script :)
