### ISSUE TITLE
Allow showing partially loaded Streams affects images

### ISSUE THREAD

**Issue by LeGiTiM** [qsniyg/maxurl#629]
Hi there, and happy new year!
So, this is more of a misleading UI problem (lack of info) than a real bug, however it caused me a hindrance for months (I thought until today that it was a limitation of the script (vs extension on firefox) or API on chromium browsers, so I just lived with it with my chromium-browsers), and a couple of hours of headache today (when I had to reinstall Firefox Nightly from scratch due to a problem, and had to import settings from my chromium browser). In hope that this will prevent other people to go through the same annoyances... Here I go:

The setting Popup > Open Behavior > Allow showing partially loaded > Streams
... affects images on sites listing a lot of images  (like google image results, or twitter and many others, etc): it turns most images into blob:url or data:url , which are "priviledged/special" and can't be affected by any extension (mouse gestures, image manipulation extensions, etc), and even cause native handling problems on several browsers (some browsers are not able to display blob image in their own tab, for example).

I think that the cause of this unexpected conversion is needed to be able to popout "streams" elements, and it will take you time to figure out if there is a way to prevent your method from affecting images on this kind of websites; so I think that for now, the best solution for everyone would be that you add a warning in the description of this option that informs of these possible problems. 
**_Also, I'm not sure it's a good thing that this option is turned ON by default in the script version._**

I've tested this on Firefox Nightly(extension), Brave Nightly, Edge, Opera (all up-to-date) : now everything works fine, and all my extensions and native functions are working perfectly on popup images, as long as i set this option to "Media" or "None". What a bliss to be able to handle them easily on chromium browsers too, now.

Thanks for reading, and for this amazing extension and hard regular work!

**Comment by qsniyg** [comment]
Good point, thank you very much for taking the time to report this! I've clarified the description with https://github.com/qsniyg/maxurl/commit/fb6d6564290706ef8bd8234da9de26295484868d.

>I thought until today that it was a limitation of the script

The reason data urls are used by default is because otherwise any image that requires custom headers (usually referer headers) will be broken (unless the right headers are by chance added by the browser, such as when you're on the host page of the image).

>it turns most images into blob:url or data:url , which are "priviledged/special" and can't be affected by any extension

While I understand & agree with your point, just for clarity, afaik only blob urls are like this. Data urls should be able to be interacted with like any other url, as the browser treats them seamlessly like any other url. For example, if you were to send a head or get request to a data url, the browser will reply like as if you sent a request to a normal http url.

However, many extensions do not account for the possibility of data urls. They treat url strings as "cheap", and will therefore avoid smart memory management, which can lead to OOM situations pretty quickly, especially in the case of bulk image download extensions unfortunately.

>I think that the cause of this unexpected conversion is needed to be able to popout "streams" elements

Actually blob urls are thankfully only needed for HLS/DASH streams (there's no way around that unfortunately, as they need to basically generate a video file on the fly). In fact, the reason why the option is set to "Streams" instead of "None" for the userscript is that downloading audio/video streams entirely before displaying them would not be a very good idea (unless they were very short). That being said, I should probably implement an option to only fully load media < a specified size (and partially load anything above it), similar to the GM_download option.

Feel free to report if there are other issues like this by the way, if there isn't already a way to do it, I'll try my best to accommodate feature requests wherever I can :)
