### ISSUE TITLE
instagram video downloading no longer works

### ISSUE THREAD

**Issue by Primpulox** [qsniyg/maxurl#660]
i don't know if this is an issue that is only affecting me but i haven't seen anyone mention this issue. hovering over IG pictures will let me right click it and save it however videos will show a grayed out save button. i seem to recall being able to download videos so maybe changes in IG's API?

**Comment by qsniyg** [comment]
>however videos will show a grayed out save button

Is this when you right click on the popup video? If so, it could be that it's using the HLS/DASH stream instead, which cannot be saved normally.

If you're not on Firefox (it's broken there unfortunately), you can go to the options page and enable "Enable downloading HLS/DASH streams" (under Popup -> Audio/Video).

Otherwise, I'd recommend one of the following:

 * Enable writing to clipboard (under the General section), use Shift+C to copy the link to the dash manifest, then send it to youtube-dl like this: `youtube-dl '[paste here]' -o video.mp4`
 * Disable HLS/DASH support ("Allow HLS/DASH streams", right above the option for downloading them). This will use regular videos, but these are often of lesser quality than the DASH ones.

**Comment by qsniyg** [comment]
Should be fixed in 0.18.0, but please let me know if not!
