### ISSUE TITLE
Extension Error 

### ISSUE THREAD

**Issue by Nzzyme** [qsniyg/maxurl#669]
Getting error with updated Chrome version (89.0.4389.72 (Official Build) (64-bit))

Please fix

https://prnt.sc/10bu5xb

**Comment by qsniyg** [comment]
These are warnings, but does it cause any problems with the extension? As far as I know they're harmless...

The reason why these exist is because the manifest file is shared between chrome, firefox, and opera, which all require different keys. Each browser will warn about certain (but different) keys being unsupported, because they don't support the keys the other browsers require, but this shouldn't cause any problems.

**Comment by Nzzyme** [comment]
Thanks. No issues observed in the functionality though.

**Comment by qsniyg** [comment]
Cool! I'll close this then :)
