### ISSUE TITLE
xiaohongshu.com

### ISSUE THREAD

**Issue by doio** [qsniyg/maxurl#688]
URL: `https://www.xiaohongshu.com/discovery/item/5fc68b8e000000000101db9c`

PIC: 
`https://ci.xiaohongshu.com/bd871b0f-f9e7-54da-fd39-80b6af034dad?imageView2/2/w/100/h/100/q/75`

→ `https://ci.xiaohongshu.com/bd871b0f-f9e7-54da-fd39-80b6af034dad`

**Comment by qsniyg** [comment]
It should already be supported, it works fine for me if I use the popup... does it not work for you?

**Comment by doio** [comment]
Oh, I can see the rule is already there but unfortunately no. I am sing Firefox and when I paste the link in the address bar and hit go, a download window will pop up and the file type is `application/octet-stream (1.9 KB)` and so it will not automatically rename. Is there any workaround regarding this? (hopefully)

**Comment by qsniyg** [comment]
Right, I don't actually know if it's possible to fix this though. Even if it is, it might cause some serious problems due to possibly being too overreaching (incl. likely performance issues), as it would need to change the way any new url is handled, not just the ones the extension has opened.

How did you find the url? If it's linked on a page, you can enable "popup for plain hyperlinks", and then open the popup that way, which'll give the original image. If it's an image, the popup should work without any options. If the reason you're opening it in a new tab is because you'd rather have it open in a new tab, rather than in a popup, you can configure the popup to do this though "Popup Action" (or add a new separate trigger to support both popup and new tab).

Sorry I know this isn't a perfect solution, but it's the only one I can think of for now...

**Comment by doio** [comment]
Thank you so much for this piece of information. In fact, I find using popups more comfortable than having to use copy-paste in the address bar. A simple mouseover and click does the trick. 

I used a greasyfork script to display the links in plain text and I felt so dumb (ಥ_ಥ) 

This is perfect for now, at least. Thank you so much again!
