### ISSUE TITLE
download instagram videos

### ISSUE THREAD

**Issue by AdClear247** [qsniyg/maxurl#716]
I use popup feature and action download and proper file name (username+id) to download photos and it works OK. But videos instead show about 1 kB file with type dash/xml. Can I download videos? Example: https://www.instagram.com/p/Bfj7odxnYm6/

**Comment by qsniyg** [comment]
Yes, it will by default open/download dash for Instagram, as dash is almost always significantly better quality than the mp4 (and sometimes higher resolution as well).

See here for solutions: https://github.com/qsniyg/maxurl/issues/660#issuecomment-782812373

That said, I could add an option to download the mp4 file instead of dash, even when dash is enabled (#717).

**Comment by AdClear247** [comment]
Disabling dash allows me to download mp4 like other extensions (media helper for ig), which is OK.
