### ISSUE TITLE
Disable by site

### ISSUE THREAD

**Issue by LukasThyWalls** [qsniyg/maxurl#75]
I think the title is self-explanatory.

It's only to add some option to disable the extension in a domain, maybe putting it in a list in options or something like that.

This is, for example, because actually i don't like how the extension manage the redirection in deviantart. Now it redirect all images to a file with name "file" but without any extension, name, author or anything else (I'm still trying to understand why [Deviantart sometimes redirect to a filename without title and author in the filename, and other times with](https://www.reddit.com/r/Archiveteam/comments/9w8b7f/recently_deviantart_changed_the_way_file/) to manage files without any filename at all, but that's another topic), but, i like how does in tumblr or other sites. That simple.

Maybe you don't want to have the redirected files in that site, or meanwhile is disabled, you can report the site here to improve the behaviour of the extensions (if it is possible). I think this is better than remember to pressing a key everytime or something like that.

Thanks

**Comment by qsniyg** [comment]
Definitely a good idea, but I'm debating a little on how to implement this. I actually intended to have a feature like this later, but after #12 was implemented (it would allow for a clean way to disable certain rules or websites). However, implementing #12 has proven to be very challenging, and I'm not sure when (or if ever) it will be implemented, as every single rule has to be rewritten (as well as a number of other challenges). So there needs to be a more immediate solution.

One way could be to just have a regex blacklist of URLs for the extension to ignore. This would obviously not be very user friendly, but it also wouldn't limit the user by creating an "easier" syntax that isn't as powerful.

I'll see if I can get this in the next release, but I'll have to think a bit on how to implement this properly. If you have any suggestions, feel free to share. It would definitely help :)

About the DeviantArt redirection issue, you're referring to when it redirects to the original downloaded version, correct? (i.e. the url has `/_api/download/file?downloadToken=...` in it) I'm not happy at all with the current state of the DeviantArt rule for a number of reasons, so I'll keep trying to look into it in order to improve it.

**Comment by LukasThyWalls** [comment]
I don't know exactly how your extension works, and i don't think i have enough knowledge to make i right point. I see others extension with a text box in options with a list of domains (one by line), and when the extension is triggered, in the beginning or when is going to make something, it checks the list with the actual domain and avoid the execution if the domain exists. For example, for deviantart should be something in the list like "wixmp.com" or "wixmp", and then when the url is "https://*wixmp.com*/*" or "https://*wixmp*/*" the redirection doesn't trigger.

For sure something simple like this can throw some errors or some undesired behaviours with wrong typed domains, but it something more simple and should work most of the time, and maybe later can be done something better, including sub-domains and other things.

But maybe this is very hard to do this at the time and you need to do a complete rewrite.

> About the DeviantArt redirection issue, you're referring to when it redirects to the original downloaded version, correct? (i.e. the url has `/_api/download/file?downloadToken=...` in it) I'm not happy at all with the current state of the DeviantArt rule for a number of reasons, so I'll keep trying to look into it in order to improve it.

Since last year, when they made some changes, the filenames when you download an image are completely screwed. Most of the time works fine, but a lot of times you have a weird filename without the title and the author, things very useful to keep track what are you downloading. And i never found a reason for that, because that seems happens randomly to some images.

The problem i refered is that, the filename of the original version is "file" without extension and nothing. I prefer to have a smaller version and keep track if i need a bigger file, than rename every file manually (I do with that weird filenames now, but i don't want to do with every image downloaded from deviantart, that's why disabling for now for deviantart it's a good idea).

**Comment by qsniyg** [comment]
It's very basic, but I've implemented it to some degree. I haven't tested it much though, so let me know if you run into any issues.

>the filenames when you download an image are completely screwed

Yeah, ever since they changed over to wix's system it's been weird. Although for a period of a few months, it did allow fetching the original image for any image, which was nice (they removed that feature a few months ago though).

>And i never found a reason for that, because that seems happens randomly to some images.

I think it has to do with when the image has been uploaded, although I could be wrong about that. It is the case for which images can be made larger (newer ones can't, while older ones can), so I'm guessing it's the same across the board, but that could be wrong.

**Comment by qsniyg** [comment]
I'll close this issue as I've now more or less finished implementing the basic functionality (minus error checking). Feel free to reopen if you have any issues though.
