### ISSUE TITLE
instagram videos no longer downloadable

### ISSUE THREAD

**Issue by modelfe** [qsniyg/maxurl#756]
I've noticed over the last week or two that full resolution instagram videos are no longer downloadable using the pop-up from this extension. This is possibly outside outside of the scope of this extension, but you can't actually retrieve the URL either (there's nothing to copy in the context menu, at least not in Firefox). I gather instagram has switched to HLS or something for maximum resolution videos, and I've been unable to figure out a way to download these videos any other way either. I've tried youtube-dl, FFmpeg, Video DownloadHelper, etc.

Just an example video: https://www.instagram.com/p/COxbsQ6FN7X/

**Comment by qsniyg** [comment]
See here for an explanation of the issue (+ workarounds): https://github.com/qsniyg/maxurl/issues/660#issuecomment-782812373

I think the proper solution (especially for firefox) will require fixing https://github.com/qsniyg/maxurl/issues/753, which means that the videos should be able to be downloaded on any browser, including FF. Downside would be a slight performance decrease, but it's not really that performance-heavy in the first place (especially since it's not encoding anything), so it shouldn't be much of an issue in theory. Just need to get enough time to implement it.. hopefully soon! :)

**Comment by modelfe** [comment]
Thanks for the fast reply, as always. Sorry about the duplicate issue, I somehow didn't scroll down far enough to see that one. Good luck with the fix!
