### ISSUE TITLE
Not working with i.redd.it images?

### ISSUE THREAD

**Issue by samsepiol59** [qsniyg/maxurl#77]
Example: https://i.redd.it/2b2fs8umv5131.jpg

If I do a reverse google search I can find bigger images, but the script doesn't fetch the bigger image when opening the link!

**Comment by qsniyg** [comment]
Correct, the script doesn't run a reverse image search, it instead looks to see if the URL itself is not the original image the website provides, and sees if it can get the original image from it.

To explain what I mean, here's an example from reddit:

https://preview.redd.it/7nte0k30d7p11.jpg?width=640&crop=smart&s=3045865f8ce23192e486c9f35de800bd6e2a685b

The script converts that into (by replacing `preview.redd.it` to `i.redd.it` and removing everything after `?`):

https://i.redd.it/7nte0k30d7p11.jpg

Of course, that rule is specific to reddit, so the script currently has ~2500 rules like that one for various different websites (although some rules, such as Flickr, are a little more complicated as they work by querying an API instead of just replacing a URL).

As such, it's more designed to be used in conjunction with a reverse image search, as they sometimes don't link to the original images, but rather scaled down (or sometimes scaled up) versions that the websites provide.

For the specific example you gave, even though there are larger versions that exist on the internet, it's the original image stored on reddit's servers, so the script is unable to do anything.

I hope that answers your question, and sorry for the confusion with the script's purpose, I'm not very good at descriptions haha :)
