### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by isBoom** [qsniyg/maxurl#771]
This script causes the volume to be uncontrolled by scrolling the mouse wheel when viewing the "https://www.bilibili.com/" website in full screen.

**Comment by isBoom** [comment]
I didn't try other video sites

**Comment by qsniyg** [comment]
Thanks for reporting! This one turned out to be quite tricky, but it looks like it's actually stemming from a Chrome bug, where the (deprecated) `mousewheel` event doesn't get fired if the `wheel` event is handled, but only if `mousewheel` is listening on `document` (and not on any other elements).

I've worked around it by just forcing the event to fire for bilibili.com. Not an ideal solution, but the only reasonable one I can come up with for the moment.

(bilibili.com should really switch to using the `wheel` event instead of `mousewheel`+`DOMMouseScroll` though)
