### ISSUE TITLE
Cannot find larger image in instagram 

### ISSUE THREAD

**Issue by channikon** [qsniyg/maxurl#778]
Before, the add-on can find larger image (1440x1440 or 1440x1800) in Instagram.
But in these few days, the add-on can only analysis 1080x1080 or 1080x1350 image in Instagram.
Please fix it thank you very much!!!!

**Comment by qsniyg** [comment]
To fix this, enable "Instagram: Use native API" under the Rules tab. However, please read below!!

The reason this was disabled by default in 0.19.1 was because Instagram has made a recent update (as of a few days ago) where they seem to lock (or even ban) accounts if they use the native API too much. My recommendation would be not use it frequently, and if possible, use a backup account. I do have a few ideas on how to work around this, but I don't have much time yet to experiment unfortunately.

By the way, in case something like this happens in the future, I always try to write any important change in the release notes. You can view them either through [the CHANGELOG.txt file](https://github.com/qsniyg/maxurl/blob/master/CHANGELOG.txt) or in [the version history for the Firefox addon](https://addons.mozilla.org/en-US/firefox/addon/image-max-url/versions/) :)

**Comment by channikon** [comment]
Thanks for your explanation!
Thank you very much!

M.C. ***@***.***> 於 2021年5月29日 週六 下午1:33寫道：
