### ISSUE TITLE
i.stpost.com

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#786]
https://i.stpost.com/dakine-flow-snug-fit-surf-shirt-upf-50-plus--short-sleeve-for-women-in-black~p~36gvv_02~460.1490.jpg 460x460
https://i.stpost.com/dakine-flow-snug-fit-surf-shirt-upf-50-plus--short-sleeve-for-women-in-black~p~36gvv_02~1500.1490.jpg 1500x1500
https://i.stpost.com/dakine-flow-snug-fit-surf-shirt-upf-50-plus--short-sleeve-for-women-in-black~p~36gvv_02~1500.jpg 1388x1388

https://i.stpost.com/dakine-flow-snug-fit-surf-shirt-upf-50-plus--short-sleeve-for-women~a~36gvv_2~1500.1.jpg 1313x1313
https://i.stpost.com/dakine-flow-snug-fit-surf-shirt-upf-50-plus--short-sleeve-for-women~a~36gvv_2~1500.jpg 1313x1313

**Comment by qsniyg** [comment]
My guess is that the 1490 one is a cache error (they requested it, realized it was wrong, then updated the image). So any new queries will result in the updated image rather than the first one. I don't think there's anything I can do about this.

The part at the beginning is just filler, for example:

`https://i.stpost.com/dakine-flow-snug-fit-surf-shirt-upf-50-plus--short-sleeve-for-women~a~36gvv_2~1500.1.jpg`
`https://i.stpost.com/~a~36gvv_2~1500.1.jpg`

However, changing even one letter of the 1490 one results in it changing to the cropped version.

**Comment by qsniyg** [comment]
I've supported it (with support for original images), but the cache issue is still there (it will redirect to the new image). I'm not sure what exactly to do about it. My guess is that it's an isolated incident, but let me know if it isn't.
