### ISSUE TITLE
Firefox addon not updated to v0.19.2

### ISSUE THREAD

**Issue by NekoAlosama** [qsniyg/maxurl#808]
https://addons.mozilla.org/en-US/firefox/addon/image-max-url/
![Screenshot_123](https://user-images.githubusercontent.com/47763383/121756746-33316d00-cae9-11eb-95af-a28a41a080fc.png)
![Screenshot_122](https://user-images.githubusercontent.com/47763383/121756747-34629a00-cae9-11eb-8b50-d79f412add3e.png)

**Comment by qsniyg** [comment]
I have submitted it, but there appears to have been a stall on some of the addons queued before it for review:

![firefox_stall](https://user-images.githubusercontent.com/20496822/121756850-63b8dd00-cad0-11eb-887e-5002d90e8d70.png)

Usually it only takes a minute or so though, so once they clear the stall it should (hopefully) be good to go.

You _can_ sideload it in the meantime (through about:debugging), but unfortunately there's no way to keep it installed after restarts (the about:config option is disabled on non-developer builds). I'll spare you my rant on how I feel about that ;)

**Comment by youk** [comment]
Was it removed altogether from AMO? https://addons.mozilla.org/en-US/firefox/addon/image-max-url/ is not valid anymore.

**Comment by qsniyg** [comment]
It was, yes. I'm not entirely sure if I can get it back, but I'll try my best.

Their reason is the following (paraphrasing for conciseness):

 1) Established libraries must be included from their official source, in their original format without any modification
   - I'm not sure how I'm going to fix this, because the reason they're modified is due to either the script requiring shims in order for them to be used, or that the libraries themselves need to be patched because the websites that need them used a patched version (e.g. in the case of slowaes).
   - Note that the process in which they're modified can be inspected (and replicated) here: https://github.com/qsniyg/maxurl/blob/master/lib/build_libs.sh . This _was_ fine for AMO, but clearly not anymore.
 2) It (somehow) violates their [acceptable use policy](https://www.mozilla.org/en-US/about/legal/acceptable-use/).
   - They did not elaborate any further on what specifically it violates. This isn't the first addon they have disabled for this reason without explaining how/why. Strangely, they did elaborate for all the other points.
   - I've looked through it, and frankly, I'm not sure how it violates it. The closest I can find is "Upload, download, transmit, display, or grant access to content that includes graphic depictions of sexuality or violence". Yes, it _can_ be used to display images containing graphic depictions of sexuality or violence. It can also be used to display... anything else. It's a tool, just like Firefox. It does contain support for sites that are generally used for this, but the _exact_ same can be said about uBlock or Imagus (they support many of the same sites generally used for sexually explicit content).
 3) The addon was missing a privacy policy
   - Good call, I've added one. Basically, it doesn't track or collect any information, but I can't do anything about websites using it for fingerprinting (since using it can theoretically be detected).

**Comment by qsniyg** [comment]
With 0.19.3 released, they got back to me on what they meant by violating their acceptable use policy, confirming that it was indeed "Upload, download, transmit, display, or grant access to content that includes graphic depictions of sexuality or violence".

I'm genuinely confused.

Both Imagus and Hover Zoom+ contain hard-coded support for websites devoted to displaying sexual content (I will not list the sites, but you can easily find them if you look through their source code). Imagus is not only allowed, it's a recommended addon, which as I mentioned before, means it has a much more in-depth review process than regular addons like IMU. This means that it's highly unlikely that it's breaking their terms of service.

In other words, I have genuinely no idea how IMU breaks their terms of service, if Imagus and HZ+ don't.

---

Just to be entirely clear, I am _not_ calling for their removal (quite the opposite in fact). Neither am I implying favoritism or anything like that.

My personal guess as to what is going on is one of the following:

 * Their terms of service have been updated recently, and they haven't yet gotten around to Imagus and HZ+, but somehow got around an addon that has ~100x less users than both of them, on AMO at least. This isn't _necessarily_ unlikely if updates trigger reviews, as Imagus and HZ+ were last updated in April and December 2020, respectively.
 * The reviewer has a different understanding of the acceptable use policy than the ones who reviewed Imagus and HZ+

**Comment by floriensk** [comment]
Fingers crossed that it'll be sorted out somehow. Keep us updated if you get to know some news!

I just deleted the addon because of this exact issue, thought I'd reinstall it with the newer version. Was sad to see that the AMO link was invalid...

**Comment by qsniyg** [comment]
They've just asked me to resubmit, so fingers crossed! :)

**Comment by qsniyg** [comment]
They've now reinstated it!

Note that the firefox addon is at version 0.19.4 instead of 0.19.3. There's no technical difference between the versions, the reason for the bump is simply because I had to resubmit it with a higher version for it to be automatically accepted.

**Comment by NekoAlosama** [comment]
@qsniyg You might wanna unpin this issue now.

**Comment by qsniyg** [comment]
@NekoAlosama Good call, thank you!
