### ISSUE TITLE
nato.int

### ISSUE THREAD

**Issue by MinuteAd8502** [qsniyg/maxurl#835]
small: https://www.nato.int/sfor/indexinf/168/p08a/sb02081d.jpg
large: https://www.nato.int/sfor/indexinf/168/p08a/b02081d.jpg
ref: https://www.nato.int/sfor/indexinf/168/p08a/t02p08a.htm
lol took me a while to get direct url because page reacts by closing itself when open network monitor, had to use ublock origin logger: https://www.nato.int/sfor/indexinf/168/p08a/b02081d.htm

**Comment by qsniyg** [comment]
Sorry for getting back so late. Thank you very much!

Yeah, they just had a `onblur=window.close()` property, I don't think it was to prevent people from getting images, but rather as a convenience so that once they click away from the window, it gets closed. Definitely designed for a different era of the internet.. :)
