### ISSUE TITLE
Option to disable logging to console on blacklisted URL

### ISSUE THREAD

**Issue by Michael82548** [qsniyg/maxurl#848]
When I blacklist YouTube, I get 100s of logs of blacklisted URLs and it clogs up the whole console and is inconvenient for me. Please add an option to disable logging on websites. Better yet, on individual URLS as an extra option

**Comment by qsniyg** [comment]
Thanks! I've added the option to disable logging entirely (though it will still print error messages, let me know if that's a problem).

As for adding an option to onlyenable it on certain URLs, I agree that would be useful, but that would require rewriting the settings fairly significantly. I want to better support this eventually though, in order to allow arbitrary settings to be applied for different sites (and eventually superseding the current profiled settings)
