### ISSUE TITLE
za.jumia.is

### ISSUE THREAD

**Issue by ghost** [qsniyg/maxurl#867]
https://za.jumia.is/unsafe/fit-in/150x150/filters:fill(white)/product/09/25131/1.jpg?6470
https://za.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/09/25131/1.jpg?6470

https://ke.jumia.is/unsafe/fit-in/680x680/filters:fill(white)/product/52/609441/1.jpg?3848

**Comment by qsniyg** [comment]
Thumbor, and a strange one at that.

I'll try to find another way if possible, since 680x680 upscales (in fact, any number can be given, because it's unsigned). What's strange is that normally it should be possible to remove it entirely. So the original images are likely stored somewhere else. This _could_ be `/cms/product/`, which returns 400 (whereas anything else returns 404), so perhaps that method is not possible, and we need to resort to using thumbor queries.

**Comment by ayunami2000** [comment]
This seems to return a large image: https://za.jumia.is/unsafe/fit-in/9999x9999/product/09/25131/1.jpg

But I'm unsure about `fit-in` and `unsafe` parameters and if there's a better replacement for either.

**Comment by qsniyg** [comment]
Thank you very much! Yes, I believe that's correct. Though the image is upscaled, it appears to be because that specific image was stored upscaled.
