### ISSUE TITLE
Change of image URLs on tumblr 

### ISSUE THREAD

**Issue by modelfe** [qsniyg/maxurl#88]
It looks like tumblr has changed its photo URLs in the last day or so.

For example, the first image on this page: https://samirafee.tumblr.com/post/185995104082/inula-helenium-horseheal-samirafee
The URL for a smaller resolution is: https://66.media.tumblr.com/e3475fa6d7f70c48aaa6de26d86ab3c4/9136861aaa9a8d24-9d/s640x960/b4367e3961f01ca54f36bee1f7b0f20bc6b9461d.jpg
While the URL for the larger resolution is: https://66.media.tumblr.com/e3475fa6d7f70c48aaa6de26d86ab3c4/9136861aaa9a8d24-9d/s1280x1920/383e0cb21ee4574703c2174ba726e63a1e1a8f15.jpg

It only seems to affect newly uploaded images; images uploaded before yesterday still have the old URL format. I assume the unique identifier that's now appended to the end of the URL will make this difficult to get around. You can always find the 1280 version of the image on the blog page, but of course you need to know the blog page where the image is uploaded, which won't always be the case.

**Comment by qsniyg** [comment]
Thanks for letting me know! The last part appears to be some kind of hash, to prevent people from changing the URL. If you look at, https://clasicmonet.tumblr.com/post/186005790899/via-piariverola-instagram, you can see the element here:

```
<figure class="tmblr-full" data-orig-height="933" data-orig-width="750">
  <img src="https://66.media.tumblr.com/77ccf0e8e37a6c637d5b2af5876a3392/b19c0bb01ed69864-d3/s500x750/b507240557eb80cba26396c87d95280122311f30.jpg" data-orig-height="933" data-orig-width="750" data-media-key="77ccf0e8e37a6c637d5b2af5876a3392:b19c0bb01ed69864-d3" width="500" height="622" alt="image" />
</figure>
```

The fact they added a `data-media-key` attribute (which is just the first 2 parts of the URL, with `/` replaced to `:`), makes me believe they might have a (private?) API that will allow you to find more information about the image, but I haven't found any indication of this yet.

I'll leave this issue open, as I'll do some more digging, but this won't be a quick solve unfortunately.

**Comment by qsniyg** [comment]
I believe the only way this can be supported is by a host-specific rule for Tumblr, as the last part appears to be a signature, meaning it cannot be modified without knowing the algorithm used to generate it (as well as, very likely, the keys).

**Comment by dogancelik** [comment]
I found a way to get the higher quality images using the new "NPF" API, it requires an API key though.
Because API keys are rate limited, Max URL users should set their own key in `https://qsniyg.github.io/maxurl/options.html`.

You need to register an app [here](https://www.tumblr.com/oauth/apps).

Then for this [page](https://samirafee.tumblr.com/post/189567617202/kerovous-own-picture-337-my-friend-and):

* Blog name is: `samirafee`
* Post ID is: `189567617202`
* Your app's consumer key

So you send a GET request to:

```
https://api.tumblr.com/v2/blog/[blog name]/posts?api_key=[consumer key]&id=[post id]&npf=true
```

`npf=true` is required, otherwise, it will not give all images.

Under `response.posts[0].trail`, you will get the images with all resolutions.

![image](https://user-images.githubusercontent.com/486818/71573664-25a34580-2af6-11ea-95e2-2bfb96a70313.png)

**Comment by qsniyg** [comment]
@dogancelik Thank you very much!! I was hoping not to need to use the API, but I guess there's no other way for the moment. I'll probably also add support to fall back to the `/image/` trick if the API key is not present, in case the user is trying to access the first image.

**Comment by fireattack** [comment]
I assume the /image/ trick only works for mouse over? Because it doesn't work in direction here.

**Comment by qsniyg** [comment]
@fireattack Correct, as far as I know, there's unfortunately no way to find the post ID from the image unfortunately, so you need to be on the blog hosting the image for the script to be able to query the API for the post ID (like Instagram).

**Comment by qsniyg** [comment]
Tumblr is now supported as a URL rule: https://github.com/qsniyg/maxurl/commit/f6c98b3fbcba6267ae58e84ae0bf394bf8c091d4

This is because Tumblr will now redirect to the HTML page hosting the image if `Accept: text/html` is sent as a header. This also allows the original blog post to be found from the image!

**Comment by modelfe** [comment]
Love the new URL rule!

Just thought I'd add here, rather than start a new issue, that the following format should redirect the standard 64x64 avatar to higher resolution:

https://api.tumblr.com/v2/blog/yesterdaysprint.tumblr.com/avatar/512

So

https://66.media.tumblr.com/7378b1813629aa8b841f6079ab9303a4/e24e926459952d1b-b1/s64x64u_c1/c7acf4139f2981e5d3ddaa6686e9240f3cf6f98d.jpg

becomes:

https://66.media.tumblr.com/7378b1813629aa8b841f6079ab9303a4/e24e926459952d1b-b1/s512x512u_c1/b76511f738556082dae60f211315787101c7dab6.jpg

AFAIK, 512 is the highest resolution for avatars.

**Comment by qsniyg** [comment]
@modelfe Thanks! Should be fixed now :) https://media.tumblr.com/7378b1813629aa8b841f6079ab9303a4/e24e926459952d1b-b1/s999999999x999999999/f68bfef37a5609bff708efb5c609f2b947201d42.jpg

It returns a 128x128 image, which I believe would be the largest unscaled version (it seems like the one you sent was upscaled)

**Comment by modelfe** [comment]
Gosh you're quick! Thanks
