### ISSUE TITLE
[url] notion.so/blog/

### ISSUE THREAD

**Issue by dym-sh** [qsniyg/maxurl#895]
`https://www.notion.so/cdn-cgi/image/w=3840,q=100/https://images.ctfassets.net/spoqsaf9291f/3W8spPYN3tFTRplzwg5LAW/883eebba0def38757f5c50eb5a414222/static-site-rfc.png`
\>\> `https://images.ctfassets.net/spoqsaf9291f/3W8spPYN3tFTRplzwg5LAW/883eebba0def38757f5c50eb5a414222/static-site-rfc.png`
(via `https://www.notion.so/blog/migrating-notion-marketing-to-next-js`)

tech: https://www.contentful.com/developers/docs/references/images-api/

**Comment by qsniyg** [comment]
Thank you! I'm not exactly sure what this system is called (I don't _think_ contentful is related, as it appears to be the destination, rather than the source).

I could make the https?:// urls as a generic rule, but I'm not sure if relative paths (such as https://blog.corp-site.envato.com/cdn-cgi/image/width=1200,quality=95,format=auto/uploads/2021/01/UX-Tips-from-Envatos-Newest-Recruits.jpg , as you reported in #638 ) can be done in a safe way (as I assume the root path can be configured).
