### ISSUE TITLE
Why is this not available as an installable extension on Chrome/Opera? 🤔

### ISSUE THREAD

**Issue by AA-Admiral** [qsniyg/maxurl#900]
### **Hello to all the devs of this project 😁👋**

Now I've been using this tool for quite a while now, early on as a userscript, then as a Firefox extension...

Now what confuses me, is why is this not available as an easy to install listing on chrome/opera stores? 🤔
I tried looking for it to install on Opera for another PC, yet I couldn't find it...

Anyway, a few eternities later,⏰ I managed to find and sideload the .CRX file into Opera anyway. 😅
I'm just really curious about this issue.

many many thanks to all the people working on this tool, it's really a great tool. 😎

![One Eternity later](https://c.tenor.com/OrYokHfK4CAAAAAC/movie-one-eternity-later.gif)

**Comment by qsniyg** [comment]
For Chrome, see https://github.com/qsniyg/maxurl/issues/28. It violates their policies because it allows you to download streams.

For Opera, it _is_ on their store (https://addons.opera.com/en/extensions/details/image-max-url/), but it can only be installed (or viewed) on beta/developer builds. This is because it uses automatic verification, as manual verification is infeasible due to the size of the extension.

Glad you found a solution! You can also download the repository, enable developer mode, and load it as an unpacked extension. This also has the added benefit of allowing you to more easily edit the addon, as well as using git to update it :)

I'm really happy you enjoy it! :)

**Comment by DevWannabe-dot** [comment]
> For Opera, it _is_ on their store (https://addons.opera.com/en/extensions/details/image-max-url/), but it can only be installed (or viewed) on beta/developer builds. This is because it uses automatic verification, as manual verification is infeasible due to the size of the extension.

Well, I checked the link and it's not available anymore. Btw congrats OP on #900 th issue XD

**Comment by qsniyg** [comment]
@DevWannabe-dot I think it's still available, but it'll return 404 if you're using anything other than the opera beta/developer builds.

By the way, thanks indirectly for reminding me to check my email (wanted to make sure opera didn't remove it or something). Turns out Greasyfork took down the userscript a few days ago and I wasn't aware lol.

**Comment by DevWannabe-dot** [comment]
Oh, I get it! And I saw that greasyfork thing earlier today haha why though?

**Comment by DevWannabe-dot** [comment]
#903 Oh I get it now :P big ups dude
