### ISSUE TITLE
DeviantArt image fails to redirect to better version

### ISSUE THREAD

**Issue by nywilds** [qsniyg/maxurl#93]
The image here https://www.deviantart.com/f1x-2/art/Nightfall-800934586 doesn't redirect at all. However in the image URL I was able to change `q_75` to `q_100` and got an image without jpg artifacts, so there is a better version available, although not necessarily bigger.

Edit: I'm using the Firefox extension.

**Comment by qsniyg** [comment]
DeviantArt definitely stepped up their security there. While you can scale down as much as you want, removing the w/h modifiers, or adding even a single pixel to them, results in 403.

Since the image is not publicly available for download, unfortunately it can't do anything about finding a larger image, but I'll add support for the `q_100` feature, thanks for letting me know!

**Comment by qsniyg** [comment]
Sorry for taking so long to fix this! Although the `q_100` feature was added [pretty quickly](https://github.com/qsniyg/maxurl/commit/773b5e66d4395200ae8dba0907bd5915f1931875#diff-27f9d4a32bb1055d6e25712679ce34afR7082), the specific image you sent exposed a bug in the actual engine processing the rules, and I couldn't seem to figure out how to fix it.

Should be working now, thanks again for reporting :)
