### ISSUE TITLE
hayabusa.io

### ISSUE THREAD

**Issue by fireattack** [qsniyg/maxurl#98]
`https://hayabusa.io/abema/programs/386-48_s0_p25/thumb001.q85.w640.h360.v1534496588.webp`
-->
`https://hayabusa.io/abema/programs/386-48_s0_p25/thumb001.png`

Got it from https://abema.tv/channels/abema-radio/slots/Eoma5fHFqq72Qw

(Also `https://hayabusa.io/abema/programs/386-71_s2098_p1/thumb001.q85.w640.h360.v1539225877.webp` )

I believe it used to work (and I saw some regex for `hayabusa.io` in user.js), but these particular ones don't work now.

**Comment by qsniyg** [comment]
Thanks for letting me know! Fixed in https://github.com/qsniyg/maxurl/commit/c2c5de942103598be6bbbc13897508444a811b1a

The issue was that it was only looking for images within `openrec-image`, and that it was only looking for numbers in the main filename (instead of also including `thumb`).

I'll keep trying to see if the rule can be improved though.

**Comment by fireattack** [comment]
I found that we should keep q with 100.

https://hayabusa.io/abema/programs/386-48_s0_p25/thumb001.q100.webp is bigger than 
https://hayabusa.io/abema/programs/386-48_s0_p25/thumb001.webp

and indeed has better quality (compared the pixels).

**Comment by qsniyg** [comment]
Thanks again! Fixed in https://github.com/qsniyg/maxurl/commit/97f35496288e0b8b11bc1c8793f92e4018e13cde.

I often forget about quality, I should probably look through older rules to see if they downgrade quality haha.
